public/pages/workflow_builder/workflow_builder.tsx
public/render_app.tsx
public/store/index.ts
public/store/reducers/index.ts
public/store/reducers/workspace_reducer.ts
public/store/store.ts

Sets up the initial redux infrastructure for maintaining frontend state. We choose to use redux / react-redux / redux-toolkit libraries since it is the consistent way that core OSD + other plugins use, and is the standard across modern react applications. It also doesn't add any dependencies since we consume them from core OSD.
- sets up global redux store via `configureStore`
- sets up basic workspace reducer to process workspace-related state updates via `createSlice`
- wraps the entire app within a `Provider` so React components have access to the store
- sets up sample cmds for future reference as ways to access and set the store in the base `WorkflowBuilder` page
Tested with some basic functionalities, including adding some dummy components, and validating if there are changes. These …

Set up redux infrastructure

---

public/component_types/base_interfaces.ts
public/component_types/index.ts
public/component_types/indices/index.ts
public/component_types/indices/knn_index.ts
public/component_types/processors/index.ts
public/component_types/processors/text_embedding_processor.ts
public/pages/workflow_builder/components/index.ts
public/pages/workflow_builder/components/input_field_list.tsx
public/pages/workflow_builder/components/input_fields/index.ts
public/pages/workflow_builder/components/input_fields/json_field.tsx
public/pages/workflow_builder/components/input_fields/select_field.tsx
public/pages/workflow_builder/components/input_fields/text_field.tsx
public/pages/workflow_builder/components/new_or_existing_tabs.tsx
public/pages/workflow_builder/index.ts
public/pages/workflow_builder/workflow_builder.tsx
public/pages/workflow_builder/workflow_component.tsx
public/utils/constants.ts

This PR accomplishes 3 main things:
1. Sets up the base interfaces that will represent all of the different building blocks / UI components users will select to construct workflows.
2. Implements interfaces for 2 components: 1/ a text embedding processor, and 2/ a k-NN index.
3. Sets up a basic `WorkflowComponent` React component that's purpose is to take in a component instance (a particular k-NN index, for example), and dynamically render based on its configuration. An example with more details is shown below.
Example:
- shows the same `WorkflowComponent` building out instances of a text embedding processor and a k-NN index.
- k-NN index component supports creation, so it has a tabbed portion to toggle the inputs based on if user wants to create a new index, or use existing
- based on …

Add initial component interfaces & basic node rendering

---

package.json
yarn.lock

Adds [ReactFlow 11.8.3](https://www.npmjs.com/package/reactflow/v/11.8.3) as a dependency. The package works as expected after transpiling to an es5 build using custom babel loaders in core OSD (see related PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4882). This is because this plugin does not maintain any custom build configurations, and we bootstrap/build everything using linked scripts from core OSD (e.g., `yarn osd bootstrap`).
Confirmed that after adding this and importing reactflow modules, there is no compilation errors. …

Add ReactFlow 11.8.3

---

common/constants.ts
common/index.ts
common/interfaces.ts
public/route_service.ts
public/store/reducers/index.ts
public/store/reducers/opensearch_reducer.ts
public/store/store.ts
server/routes/helpers.ts
server/routes/opensearch_routes.ts

This PR adds support for e2e processing of fetching visible indices. It does this by:
1. Adding a server-side `cat.indices` route, a client-side fn in the `RouteService`, and a redux thunk fn in a new `opensearchSlice` reducer. This follows the modern pattern of async / server-side data handling with redux. For more details, see https://redux.js.org/tutorials/fundamentals/part-8-modern-redux#writing-thunks
Makes progress on #6, #10

Add redux thunk fns; add cat indices API

---

common/index.ts
public/component_types/indices/knn_index.ts
public/component_types/interfaces.ts
public/component_types/processors/text_embedding_processor.ts
public/pages/workflow_detail/workspace/workspace.tsx
public/pages/workflow_detail/workspace_component/workspace_component.tsx
public/store/reducers/workflows_reducer.ts

This PR adds the custom node type which references the `WorkspaceComponent`. This is the single custom node type we will use to render all of the different types (e.g., text embedding processor, knn index, etc.). Short demo of those components in the ReactFlow workspace shown below.
Also does minor comment cleanup and removes the `init()` fn for now. We will likely need some helper fns for these classes later on, but removing what's not needed for now.
[screen-capture (11).webm](https://github.com/opensearch-project/opensearch-ai-flow-dashboards/assets/62119629/28ae7fdd-fe40-43d7-acf8-37aca779deaf)
Makes progress on #10, #16
For more information on following Developer …

Onboard custom node type to Workspace

---

common/index.ts
public/component_types/indices/knn_index.ts
public/component_types/interfaces.ts
public/component_types/processors/text_embedding_processor.ts
public/pages/workflow_detail/workspace/reactflow-styles.scss
public/pages/workflow_detail/workspace/workspace.tsx
public/pages/workflow_detail/workspace_component/input_handle.tsx
public/pages/workflow_detail/workspace_component/output_handle.tsx
public/pages/workflow_detail/workspace_component/utils.ts
public/pages/workflow_detail/workspace_component/workspace_component.tsx
public/store/reducers/workflows_reducer.ts
public/utils/constants.ts
public/utils/index.ts
public/utils/utils.ts

This PR adds the input and output handles to the general `WorkspaceComponent`. Specifically, we add an `InputHandle` and `OutputHandle` class which adds the `Handle` reactflow component dynamically based on the component spec. These classes configure the data within the input and output handles so they can be processed correctly.
Also adds a custom `isValidConnection` helper fn to determine if a connection from a source to target is allowed. Currently, we do basic validation that 1/ the base classes are the same and 2/ prevent multiple connections if the input handle does not allow it. Short video below demonstrates this.
Current logic assumes the output handle may be multiple classes (string[]). These are serialized/deserialized by turning them into a pipe-delimited string. The input …

Add input and output handles to components

---

public/pages/workflow_detail/workspace/reactflow-styles.scss
public/pages/workflow_detail/workspace/workspace.tsx
public/pages/workflow_detail/workspace_component/input_handle.tsx
public/pages/workflow_detail/workspace_component/output_handle.tsx
public/pages/workflow_detail/workspace_component/workspace_component.tsx
public/pages/workflow_detail/workspace_edge/deletable-edge-styles.scss
public/pages/workflow_detail/workspace_edge/deletable_edge.tsx
public/pages/workflow_detail/workspace_edge/index.ts
public/store/context/react_flow_context_provider.tsx

This PR enhances the reactflow edge used in the Workspace. Specifically:
- adds a `DeletableEdge` component based on the [buttonEdge](https://reactflow.dev/docs/examples/edges/custom-edge/) provided in ReactFlow docs. When a user makes a connection, an 'X' button is shown in the middle. When clicked, the edge is deleted.
- implements `deleteEdge()` in the reactflowcontext.
- adds the `DeletableEdge` class as the single edge type in the `ReactFlow` instance.
- adds dynamic styling using [reactflow styling classes](https://reactflow.dev/docs/guides/theming/#react-flow-class-names) to dynamically color the edge handle to red or green based on if the connection is valid or not before a user attempts to connect. See demo video for example.
Makes progress on #8 , #10 , #16 , #18 …

Add edge deletion and custom edge styling

---

common/interfaces.ts
public/component_types/base_component.tsx
public/component_types/indices/knn_index.ts
public/component_types/processors/text_embedding_processor.ts
public/pages/workflow_detail/components/header.tsx
public/pages/workflow_detail/utils/index.ts
public/pages/workflow_detail/utils/utils.ts
public/pages/workflow_detail/workspace/workspace.tsx
public/store/reducers/workflows_reducer.ts
public/store/reducers/workspace_reducer.ts

This PR does a few different things:
1. Cleans up `Workflow` serialization in a few different ways: 1/ We now store the reactflow state under `workspaceFlowState` field in a `Workflow`. We do some post-processing on the nodes so we don't store unnecessary data in the state. 2/ Serialize the workspace components (knn index, text embedding processor, etc.) by converting class -> obj. To do this we add a `toObj()` fn in a base component class that all of the component classes extend. We may have future utility functions added here so this sets that up.
2. Sets up stub functions for the save workflow steps, including flow validation & use case template generation.
3. Remove `components` field from the `workspace` reducer, since we simply utilize the ReactFlowInstance for keeping this state. …

Clean up obj serialization; set up save workflow stub fns

---

public/app.tsx
public/pages/overview/overview.tsx
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workspace/component_details.tsx
public/pages/workflow_detail/workspace/component_inputs.tsx
public/pages/workflow_detail/workspace/index.ts
public/pages/workflow_detail/workspace/reactflow-styles.scss
public/pages/workflow_detail/workspace/resizable_workspace.tsx
public/pages/workflow_detail/workspace/workspace-styles.scss
public/pages/workflow_detail/workspace/workspace.tsx
public/pages/workflow_detail/workspace_component/input_field_list.tsx
public/pages/workflow_detail/workspace_component/workspace_component.tsx
public/pages/workflows/new_workflow/new_workflow.tsx
public/pages/workflows/workflow_list/workflow_list.tsx
public/pages/workflows/workflows.tsx

This PR adds a resizable panel that dynamically shows component details based on the selected component in the ReactFlow workspace, using ReactFlow's [useOnSelectionChange() hook](https://reactflow.dev/docs/api/hooks/use-on-selection-change/). If none are selected, it shows an empty state. If the panel is closed, it will automatically open when a user selects a component in the workspace. The panel content replaces what used to be in the components themselves; this is where the users will view / edit / update user-provided input to the individual components. Form validation & persisting input is still a TODO.
Other details:
- nests the entire workspace in a new `ResizableWorkspace` component to contain both the ReactFlow workspace, and the new `ComponentDetails` panel.
- nests the entire …

Add a component details side panel

---

public/component_types/interfaces.ts
public/pages/workflow_detail/workspace/workspace.tsx
public/pages/workflow_detail/workspace_component/workspace_component.tsx
public/store/context/react_flow_context_provider.tsx
public/store/reducers/workflows_reducer.ts
public/utils/utils.ts

Adds a delete button to the header in the workflow component. Implements `deleteNode()` to remove the node and any related edges via `reactFlowInstance` context. Updates Workspace state as well (see video of `Save` button becoming available after deletion). Note that in order to delete, we need to propagate the ID into the `data` field of the ReactFlow component. We do this via a new `initComponentData()` fn to populate instance-specific data, such as ID. There may be more of these types of fields in the future, so we leave the new interface and fn generic.
Also cleans up the layout slightly to more closely align with UX mockups.
Demo video:
[screen-capture (16).webm](https://github.com/opensearch-project/opensearch-ai-flow-dashboards/assets/62119629/29e06bfe-f96f-4f03-82c3-351d707a381c) …

Add node deletion functionality in Workspace

---

common/interfaces.ts
public/general_components/general-component-styles.scss
public/general_components/index.ts
public/general_components/multi_select_filter.tsx
public/pages/workflow_detail/components/header.tsx
public/pages/workflow_detail/launches/columns.tsx
public/pages/workflow_detail/launches/index.ts
public/pages/workflow_detail/launches/launch_details.tsx
public/pages/workflow_detail/launches/launch_list.tsx
public/pages/workflow_detail/launches/launches.tsx
public/pages/workflow_detail/prototype/index.ts
public/pages/workflow_detail/prototype/prototype.tsx
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workspace/resizable_workspace.tsx
public/pages/workflows/workflow_list/columns.tsx
public/pages/workflows/workflows.tsx
public/store/reducers/workflows_reducer.ts
public/utils/utils.ts

This PR achieves 4 main things:
1. Adds a general & reusable `MultiSelectFilter` component that can be added to tables for filtering by subset of available options (e.g., workflow status).
2. Enhance existing workflow list table with the added filter, + with a debouncing search bar
3. Refactor the workflow details page into 3 main tabs- Editor, Launches, and Prototype, with the url path persisting the selected tab
4. Implements a basic launches table with similar multi-select filtering and debounced searching capabilities. This is added under the Launches tab. Note I've added dummy data there for testing & demo purposes.
With the refactoring, this also does some minor styling & padding changes for consistency, and adds boilerplate pages for the unfinished Launches and Prototypes pages …

Add multi-filtering to tables; refactor details pages into tabs

---

.github/workflows/draft-release-notes.yml
.github/workflows/lint.yml
DEVELOPER_GUIDE.md
README.md
common/constants.ts
opensearch_dashboards.json
package.json
public/app.tsx
public/index.ts
public/pages/overview/overview.tsx
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflows/workflows.tsx
public/plugin.ts
public/render_app.tsx
public/types.ts
public/utils/constants.ts
server/index.ts
server/plugin.ts
server/types.ts

Update GHA, constants, documentation, vars, etc. from legacy term that included "ai". 
[List any issues this PR will resolve]

Update legacy naming

---

public/pages/workflows/workflow_list/columns.tsx
public/pages/workflows/workflow_list/workflow_list.tsx
public/pages/workflows/workflows.tsx
public/store/reducers/workflows_reducer.ts
server/routes/flow_framework_routes_service.ts
server/routes/helpers.ts

This PR adds a delete action to the table to delete the corresponding workflow, and a few other minor improvements to the table. Specifically:
- adds an `actions` column with delete functionality
- finalizes Delete Workflow API response processing and hooks it into the redux store
- edge case handling of missing workflow state doc
- adds loading state by using the `loading` redux field to display a spinner when fetching workflows
- refreshes list of workflows when navigating back to the 'manage' tab, which is the workflow list page
Demo video:
[demo-229.webm](https://github.com/opensearch-project/dashboards-flow-framework/assets/62119629/f07362d1-9081-4a02-87b2-da44153eb739)
Resolves #70 
Resolves #65 
By submitting this pull request, I confirm that my contribution is made under the terms …

Add deletion to Workflow List page table

---

public/general_components/delete_workflow_modal.tsx
public/general_components/index.ts
public/pages/workflows/empty_list_message.tsx
public/pages/workflows/workflow_list/workflow_list.tsx
public/pages/workflows/workflows.tsx

This PR improves the Workflow List page and makes consistent with the mocks in a few ways:
- adds a confirmation model before workflow deletion. This will be expanded upon in the future to list out associated resources, optionally deprovision, show for all versions, etc. Making a standalone component so it can be shared across pages if needed (e.g., deleting within the details pages)
- enhances the empty list message to include an actionable button that navigates to the 'create workflow' tab
Demo:
[video.webm](https://github.com/opensearch-project/dashboards-flow-framework/assets/62119629/fd236209-4c9a-4959-8472-4337cbd671f9)
Resolves #92 
For more information on following …

[Workflow list] Add delete modal; add empty list msg

---

.github/workflows/build-and-test.yml
babel.config.js
opensearch_dashboards.json
package.json
public/pages/workflows/workflows.test.tsx
test/index.ts
test/jest.config.js
test/mocks/index.ts
test/mocks/mock_core_services.ts
test/mocks/style_mock.ts
tsconfig.json

This PR sets up the initial test coverage configuration and initial build-and-test CI to run on every pull request and push to all branches. It includes all necessary mocks for core services, redux store, and CSS files as demonstrated by the sample unit test added `workflows.test.tsx`.
Consistent with other plugins, this adds a script `test:jest` which is used to execute tests.
Check out the incredible coverage!
```
yarn test:jest
yarn run v1.22.19
warning package.json: License should be a valid SPDX license expression
$ ../../node_modules/.bin/jest --config ./test/jest.config.js
PASS  public/pages/workflows/workflows.test.tsx
Workflows
✓ renders the page (155 ms)
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.356 s
Ran all test suites. …
```

Configure unit test environment; add build & test CI

---

common/constants.ts
common/utils.ts
public/pages/workflows/workflow_list/columns.tsx
server/routes/helpers.ts

As a follow up to https://github.com/opensearch-project/flow-framework/pull/551, this PR integrates with those fields by adding the parsing logic on the server-side to persist them.
Also updates the workflow list to remove the hardcoded placeholders and render the timestamps appropriately.
Screenshot highlighting 2 un-provisioned workflows and one provisioned workflow:
none

Integrate with workflow timestamp fields

---

common/utils.ts
public/pages/workflow_detail/component_details/component_details.tsx
public/pages/workflow_detail/component_details/component_inputs.tsx
public/pages/workflow_detail/component_details/input_field_list.tsx
public/pages/workflow_detail/component_details/input_fields/select_field.tsx
public/pages/workflow_detail/component_details/input_fields/text_field.tsx
public/pages/workflow_detail/components/header.tsx
public/pages/workflow_detail/utils/utils.ts
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workspace/resizable_workspace.tsx
public/pages/workflow_detail/workspace/workspace.tsx
public/pages/workflows/workflows.test.tsx
public/pages/workflows/workflows.tsx

This PR improves the overall validation logic on the workflow editor:
- moves the save/launch buttons from the global page to embedded within the editor, and adds a delete button at the global level. This is a placeholder and may be modified or removed in the future pending final UX design.
- integrates the form state in each drag-and-drop component as part of the overall validation when clicking `Save` button. This is done by propagating callback fn `onFormChange` to the low-level form components, and performing form validation and submission when clicking `Save` button
- adds callouts if something is invalid. separate messaging for form state vs. flow state is supported (final design/wording is TBD)
- refactors the generation of the `workspaceFlowState` from `workspace` to parent …

Enforce fine-grained form and flow validation

---

common/constants.ts
public/pages/workflow_detail/component_details/input_fields/text_field.tsx
public/pages/workflow_detail/components/header.tsx
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workspace/resizable_workspace.tsx
public/pages/workflows/workflows.tsx
server/routes/flow_framework_routes_service.ts
server/routes/helpers.ts

This PR improves error handling a few different ways:
- bubbles up persisted errors as toast notifications at the top-level `workflows` page and `workflow_detail` page
- filters out unnecessary backend errors and hide on the frontend when appropriate. currently, this just means not showing an `index_not_found_exception` when executing the search workflows API so we don't show errors on a fresh cluster when loading any of the pages, for example
Testing
- ensured index_not_found_exception is hidden appropriately
- ensured toasts show for create, save, update, delete workflow failures on the base pages
- ensured there is no multiple / re-rendering of the toasts (not triggering several toasts for the same error)
Misc
- improved save state. updating the form only on change for `text_field` to …

Add error handling to top-level pages

---

common/interfaces.ts
public/component_types/indexer/indexer.ts
public/component_types/interfaces.ts
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workspace/resizable_workspace.tsx
public/pages/workflow_detail/workspace/workspace.tsx
public/store/reducers/workflows_reducer.ts
public/utils/utils.ts
server/routes/flow_framework_routes_service.ts
server/routes/helpers.ts

This PR fully onboards the get workflow API. Note we do the same logic as `searchWorkflows()`, in that we make an additional call to fetch the workflow state as well. This is to prevent bugs or edge cases where everything is present except state, and less calls needing to be made from client -> server.
Also:
- audits existing TODOs and removes irrelevant ones
- minor refactoring of `toWorkflowObj()` to reuse it in `getWorkflow()`

Onboard get workflow API

---

common/constants.ts
common/interfaces.ts
public/app.tsx
public/component_types/interfaces.ts
public/component_types/transformer/text_embedding_transformer.ts
public/pages/workflow_detail/component_details/component_details.tsx
public/pages/workflow_detail/component_details/component_inputs.tsx
public/pages/workflow_detail/component_details/input_field_list.tsx
public/pages/workflow_detail/component_details/input_fields/index.ts
public/pages/workflow_detail/component_details/input_fields/model_field.tsx
public/pages/workflow_detail/component_details/input_fields/select_field.tsx
public/pages/workflow_detail/resources/resource_list.tsx
public/pages/workflow_detail/utils/workflow_to_template_utils.ts
public/pages/workflow_detail/workspace/resizable_workspace.tsx
public/pages/workflows/new_workflow/use_case.tsx
public/utils/constants.ts
public/utils/utils.ts
server/routes/helpers.ts

This PR adds the ability to select existing models, or select from available pretrained models, in the text embedding processor component. Specifically:
- adds and updates several ML commons interfaces and constants
- enhances search model logic on server-side to parse out more details from the API responses
- adds some pretrained model constants to be optionally used when building flows
- adds a `ModelField` field type to process all of the logic around model selection, including only showing valid deployed models, and available pretrained models. _Note: the final props and how customizable this field will need to be is TBD. For example, we can customize it to be tailored towards text embedding models vs. other types of models in the future_
- updates form state and form validation to …

Add option to select and provision pretrained text embedding models

---

common/constants.ts
public/pages/workflow_detail/prototype/index.ts
public/pages/workflow_detail/prototype/ingestor.tsx
public/pages/workflow_detail/prototype/prototype.tsx
public/pages/workflow_detail/prototype/query_executor.tsx
public/pages/workflow_detail/prototype/utils.ts
public/pages/workflow_detail/utils/data_extractor_utils.ts
public/pages/workflow_detail/utils/index.ts
public/pages/workflow_detail/utils/workflow_to_template_utils.ts
public/pages/workflow_detail/workflow_detail.tsx
public/route_service.ts
public/store/reducers/opensearch_reducer.ts
server/routes/opensearch_routes_service.ts

This PR adds a Prototype tab that can be used for testing a workflow end-to-end. _Note the placement of executing this in UX is TBD, so I've placed in its own sandboxed tab for now for ease of use_. It dynamically parses out the necessary fields to generate both 1/ a valid document schema to ingest to the configured index, and 2/ a valid query to run some variation of neural search against the configured index, all based on the workflow's use case. For example, a `SEMANTIC_SEARCH` use case will have the index mapping configured with a specific set of fields (input field, vector field, model ID), defining the document schema, and a particular way to execute a search with the neural query clause utilizing those fields. This will all be different than other neural search variations, that …

Add a prototype tab; support ingest and search with guardrails

---

common/constants.ts
common/interfaces.ts
public/component_types/index.ts
public/component_types/indexer/indexer.ts
public/component_types/indexer/knn_indexer.ts
public/component_types/other/document.tsx
public/component_types/other/index.ts
public/component_types/transformer/index.ts
public/component_types/transformer/sparse_encoder_transformer.ts
public/component_types/transformer/text_embedding_transformer.ts
public/pages/workflow_detail/component_details/component_inputs.tsx
public/pages/workflow_detail/component_details/input_fields/model_field.tsx
public/pages/workflow_detail/prototype/ingestor.tsx
public/pages/workflow_detail/prototype/query_executor.tsx
public/pages/workflow_detail/prototype/utils.ts
public/pages/workflow_detail/utils/data_extractor_utils.ts
public/pages/workflow_detail/utils/workflow_to_template_utils.ts
public/pages/workflow_detail/workspace/resizable_workspace.tsx
public/pages/workflows/new_workflow/utils.ts
public/pages/workflows/workflow_list/columns.tsx
public/utils/constants.ts
server/resources/templates/neural_sparse_search.json
server/resources/templates/semantic_search.json

This PR onboards an out-of-the-box [neural sparse search](https://opensearch.org/docs/latest/search-plugins/neural-sparse-search/) workflow configuration by adding a base template, the base set of workspace nodes/edges, and updated/refactored logic in the parsing to produce a usable workflow template that can provision an ingest pipeline and index (and optionally a pretrained neural sparse model). More specifically:
- adds OOTB sparse encoder pretrained models and adds them as options in `ModelField`
- adds `SparseEncoderTransformer` ML transformer component
- minor refactoring in `Ingestor` and `QueryExecutor` to handle neural sparse use case
- refactoring in `workflow_to_template_utils` to handle neural sparse use case
- added neural sparse template so it is propagated in the "Create …

Onboard neural sparse search

---

common/constants.ts
common/interfaces.ts
public/component_types/base_component.tsx
public/component_types/indexer/indexer.ts
public/component_types/other/index.ts
public/component_types/other/query/index.ts
public/component_types/other/query/match_query.tsx
public/component_types/other/query/neural_query.tsx
public/component_types/other/query/query.tsx
public/component_types/other/results.tsx
public/component_types/transformer/index.ts
public/component_types/transformer/normalization_transformer.ts
public/component_types/transformer/results_transformer.ts
public/component_types/transformer/sparse_encoder_transformer.ts
public/component_types/transformer/text_embedding_transformer.ts
public/pages/workflow_detail/prototype/ingestor.tsx
public/pages/workflow_detail/prototype/query_executor.tsx
public/pages/workflow_detail/prototype/utils.ts
public/pages/workflow_detail/resources/columns.tsx
public/pages/workflow_detail/utils/data_extractor_utils.ts
public/pages/workflow_detail/utils/workflow_to_template_utils.ts
public/pages/workflow_detail/workspace/reactflow-styles.scss
public/pages/workflow_detail/workspace/workspace_components/workspace_component.tsx
public/pages/workflows/new_workflow/utils.ts
public/route_service.ts
public/store/reducers/opensearch_reducer.ts
public/utils/constants.ts
server/resources/templates/hybrid_search.json
server/routes/helpers.ts
server/routes/opensearch_routes_service.ts

This PR adds many changes to the I/O and appearance on the drag-and-drop workspace. Note the final inputs/outputs/component types etc. are still not finalized. The purpose for adding placeholder components and updating inputs/outputs now is to iteratively improve on and make the current state of the plugin more functional and user-friendly, and to help start gathering initial feedback. Adding the existing use cases helps provide some immediate utility and testing of the corresponding backend Flow Framework plugin.
This PR has 2 main changes: 1/ Onboarding a basic [hybrid search](https://opensearch.org/docs/latest/search-plugins/hybrid-search/) use case, and 2/ providing visible, readonly flows on the DnD workspace for better overall e2e understanding from user perspective. More details:
- …

Onboard hybrid search use case; add readonly search flows for all use cases

---

public/app.tsx
public/global-styles.scss
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workspace/resizable_workspace.tsx
public/pages/workflow_detail/workspace/workspace-styles.scss
public/render_app.tsx

This PR adds styling such that the drag-and-drop workspace area maximizes available space on the webpage. See demo video for an example.
[screen-capture (29).webm](https://github.com/opensearch-project/dashboards-flow-framework/assets/62119629/bbbe87e5-8ca7-45a3-8e21-8d8a0bca2aad)
none

Improve workspace to fit entire available page

---

public/pages/workflow_detail/components/header.tsx
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workflow_inputs/footer.tsx
public/pages/workflow_detail/workflow_inputs/index.ts
public/pages/workflow_detail/workflow_inputs/ingest_inputs/enrich_data.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/index.ts
public/pages/workflow_detail/workflow_inputs/ingest_inputs/ingest_data.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/ingest_inputs.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/enrich_search_request.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/enrich_search_response.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/index.ts
public/pages/workflow_detail/workflow_inputs/search_inputs/search_inputs.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/new_workflow/utils.ts

There has been recent changes to the proposed UX. The previous proposal was filling out inputs individually within a selected ReactFlow component. The new proposal is a more guided/structured way of filling out inputs. Now, it is form based via a single, stepped form with all of the required inputs end-to-end in one view. As users fill it out, the workspace components automatically populate based on the inputs. The workspace itself remains readonly. And for further testing, there will be a new tools view for executing ingest and search, all within the single page (no tabs / other dedicated views).
This PR handles the initial refactoring and setup of the stubbed form input components to be implemented incrementally. More specifically:
- new `WorkflowInputs` component & several child …

Initial refactoring of workflow editor page

---

common/interfaces.ts
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/ingest_data.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/ingest_inputs.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/search_inputs.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/new_workflow/utils.ts
public/utils/utils.ts

This PR adds several base interfaces used in the new form/configuration component on the workflow editor page. These are kept generic for now until more details of the form inputs are finalized from UX. The base `WorkflowConfig` will live under the new `config` field added in the `ui_metadata` interface. The main idea is this base `config` will capture all of the input in the form, and will be used for generating the 1/ form values, 2/ `yup` validation schema, and 3/ the ReactFlow workspace's nodes/edges. The initial conversion fns have been added and stubbed.
Additionally, the form & schema values in `ResizableWorkspace` (`formValues`, `formSchema`) have changed from the workspace-flow-based form/schema, to the new interfaces, since these will be the source of truth, instead of the …

Add new workflow config interfaces

---

public/component_types/other/results.tsx
public/component_types/transformer/index.ts
public/pages/workflow_detail/workspace/workspace.tsx
public/pages/workflows/new_workflow/utils.ts
public/utils/utils.ts

This PR sets up the basic conversion logic to generate the ReactFlow workspace's nodes/edges based on a WorkflowConfig. As an example, given a config with ingest processors defined under `ingest.enrich`, UI will generate a Transformer component and connect it between the initial request, and the index, to visualize the data flow. Example in screenshot below. 
More specifics:
- updates the nodes/edges initialization in `Workflow` to be dynamically generated based on the `config`, instead of using the persisted `workspace_flow`. (we may deprecate `workspace_flow` as we may not need to persist that for now, until we want drag-and-drop support)
- implements `uiConfigToWorkspaceFlow` and all of its sub/helper fns. Some are implemented and some are stubbed, will be filled out as the config …

Add initial logic to generate ReactFlow workspace

---

common/constants.ts
public/pages/workflow_detail/components/header.tsx
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/ingest_inputs.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/new_workflow/new_workflow.tsx
public/pages/workflows/new_workflow/use_case.tsx
public/store/reducers/workflows_reducer.ts

This PR updates and refactors a variety of functionality related to form validation and workflow updates, to match with the updated UX. Specifically:
- Updates the card buttons in `NewWorkflow` to read as `Create`, and update the functionality to actually create a preset workflow and load the editor page with the newly-created workflow automatically with the created ID
- Removes the notion of a `new`/temporary/cached workflow, and all related code, frontend state, and redux store logic for it. Now, the editor page can only be loaded using a created workflow in the backend with a persisted ID
- Updates the buttons in `WorkflowInputs` to match the UX. There will now be no explicit `create` buttons, and will only be `Ingest`/`Search` buttons to execute ingest and search. Internal updates to …

Update create workflow, update workflow, and form validation logic

---

public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/tools/tools.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/ingest_data.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx

This PR enables basic ingestion and viewing the ingestion response in the tools panel. Specifically:
- adds an `ingestResponse` var to persist at the global workspace level to be viewed from anywhere
- implements fns needed for performing validating/deprovision/update/provision of workflows if the user updates something (changes index name, changes/adds ingest processors, etc.). In the future we can leverage the backend fine-grained provisioning work to simplify this to 1 API call instead of 3, and allow for optimized deprovisioning (removing the requirement to deprovision things like indices or models, if a user updates some resource that is unrelated).
- perform validation/deprovision/update/provision when a user clicks 'Run ingestion'. This a pre-requisite for the configuration to be …

Enable workflow updates and document ingest

---

public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/enrich_data.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/ingest_data.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/ingest_inputs.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/processors_list.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/search_inputs.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx

This PR updates the 'Enrich data' section on ingest-related workflow inputs to support multiple processors, including the ability to add and delete them. Specifically:
- persists a standalone `UiConfig` prop to pass to all of the downstream form inputs, instead of the workflow. This way, we can decouple the form from being tied to the backend-persisted workflow config. Now, we can have a flexible, updatable `UiConfig` that we can add/remove fields (including adding/removing processors) without saving/updating in the backend. We add callbacks to the base fn to re-generate the form values & form schema when changes are made. When the users finally save, we will take this dynamic `UiConfig` field and update the underlying backend workflow with it
- adds `addProcessor()` and …

Multi-processor support & associated CRUD operations

---

public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/processors_list.tsx
public/pages/workflow_detail/workspace/workspace.tsx
public/utils/utils.ts

This PR adds support to dynamically update the reactflow nodes/edges when ingest processors are added/removed. Also cleans up & simplifies the params passed to the base `Workflow` component, as this adds the same decoupling logic as #168 , in that we use the `UiConfig` as the source of truth instead of the workflow.
Note: customization of processor types etc. will be in future PRs
Demo video:
[screen-capture (38).webm](https://github.com/opensearch-project/dashboards-flow-framework/assets/62119629/68da6564-faff-4456-b083-494835d7ad22) …

Dynamically update ingest workflow when adding processors

---

public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx

This PR adds 2 minor improvements:
- basic guardrails on clicking `Run Ingestion` - now will not execute if the json is empty or invalid
- auto-state updates of the workflow after running `Run Ingestion`. The workflow state is updated and resources are populated without a manual refresh (in the future, may have dedicated refresh button(s) for updating as well, since provisioning time is indeterminate)
Demo showing the doc guardrails (toast) and state updates after executing
[screen-capture (40).webm](https://github.com/opensearch-project/dashboards-flow-framework/assets/62119629/71fa3cde-84b0-4b37-a856-dc0690a8d9e7)
For more information on following Developer Certificate of …

Add ingest guardrails; add auto-refresh after provisioning/reprovisioning

---

common/interfaces.ts
public/configs/base_config.ts
public/configs/ingest_processors/ml_ingest_processor.ts
public/configs/ml_processor.ts
public/configs/processor.ts
public/pages/workflow_detail/utils/workflow_to_template_utils.ts
public/pages/workflow_detail/workflow_inputs/ingest_inputs/ingest_data.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/processors_list.tsx
public/pages/workflows/new_workflow/utils.ts

This PR finishes the onboarding of the ML inference processor as an available processor to add and configure, and produce a usable final workflow template. Specifically:
- adds a `Processors` clickable context menu to select available processor types when adding a processor on the UI. Currently just ML inference processor type is supported
- finishes template support of creating a single ingest pipeline step from a dynamic list of processors of all types (previously stubbed to be a single ML processor)
- cleans up `configs/` interfaces and implements `toObj()` to easily convert processors into valid fields within `WorkflowConfig` without extra code
Demo showing the new button and the dynamic addition of multiple processors: …

Finish onboarding of the ML inference processor

---

public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx

Small PR to switch the stepped input form title from explicit text to using `EuiStepsHorizontal` to match current UX.
Demo video:
[screen-capture (42).webm](https://github.com/opensearch-project/dashboards-flow-framework/assets/62119629/6d79e22b-99d6-4bb5-93fa-2d59848a93f0)

Add stepped status in input form

---

common/constants.ts
common/interfaces.ts
public/configs/index.ts
public/configs/search_request_processors/index.ts
public/configs/search_request_processors/ml_search_request_processor.ts
public/configs/search_response_processors/index.ts
public/configs/search_response_processors/ml_search_response_processor.ts
public/general_components/index.ts
public/general_components/processors_title.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/enrich_data.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/ingest_data.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/processors_list.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/enrich_search_request.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/enrich_search_response.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/search_inputs.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/new_workflow/utils.ts
public/utils/utils.ts

This PR onboards the ML inference processor in the context of search request processors and search response processors in the `WorkflowInputs` form. Specifically:
- refactors interfaces and the `ProcessorsList` component to be generic and handle ingest / search request / search response processor contexts
- adds processor configs under `configs/` for the new processors
- updates `EnrichSearchRequest` and `EnrichSearchResponse` components to take in `ProcessorsList`
- updates and adds the utility fns to handle conversion of the search config processors to/from a config to form, and vice versa
- updates the initial Semantic Search use case to have a default empty list of processors
- title updates to the form - adds a generic `ProcessorsTitle` to be reused across the processor forms, and be …

Onboard ML inference processors for search request / search response (form)

---

public/pages/workflow_detail/utils/workflow_to_template_utils.ts
public/utils/utils.ts

This PR finishes up what was started in #180. Specifically, it finishes the logic for dynamically generating the ReactFlow workspace nodes/edges, and the workflow template with a `create_search_pipeline` workflow step.
- refactors and adds logic in `workflow_to_template_utils` to generate the `create_search_pipeline` step with any configured search request and search response processors. Also updates the `create_index` step to gracefully handle the cases of no ingest or search pipeline defined, which is allowed in the UI.
- refactors and adds logic in the base `utils` to generate the dynamic list of nodes/edges in the search flow
Demo video showing the workspace flow (template configuration and testing different edge cases of search and ingest pipelines was verified manually - can't test …

Finish onboarding ML inference search request / response processors

---

common/interfaces.ts
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/tools/tools.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/advanced_settings.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/ingest_data.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/ingest_inputs.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/json_field.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/search_inputs.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/new_workflow/utils.ts
public/utils/config_to_form_utils.ts
public/utils/config_to_schema_utils.ts
public/utils/config_to_template_utils.ts
public/utils/form_to_config_utils.ts
public/utils/utils.ts

This PR achieves various functionalities. The 3 main pieces are:
1. Supporting query execution and seeing results in the `Tools` panel on the search-inputs side
2. Supporting/exposing index mappings and settings to set on the ingest-inputs side
3. Support different states on the ingest-inputs side.
More details:
- adds query state in `WorkflowInputs` similar to ingest state. When populated, shows the query results in the `Tools` component
- implements the query results tab in the `Tools` component to show the results, similar to ingest response
- adds a check and different states on the ingest-inputs side, depending on if ingest has been ran yet. Add a few things indicating in "edit" state, such as buttons and their functionalities changing
- adds index mappings and index settings as …

Support query execution; support index settings/mappings; support create/edit states for ingest

---

public/pages/workflow_detail/components/header.tsx

This PR updates the workflow detail header to show the last updated time, and repurposes the "Export" button to be a "Close" button that navigates to the workflow list page. There will be dedicated export functionality later on, within the inputs panel. Final UX TBD.
Demo video, showing the updated time automatically refreshed, and the close button navigation.
[screen-capture (41).webm](https://github.com/opensearch-project/dashboards-flow-framework/assets/62119629/13a3de24-4e58-4cae-9a95-2a1e551777af) …

Update header to show last updated and close button

---

common/interfaces.ts
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/search_inputs.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/new_workflow/utils.ts
public/utils/config_to_form_utils.ts
public/utils/config_to_schema_utils.ts
public/utils/config_to_workspace_utils.ts

Similar to the way we persist the ingest documents, we persist the query in the same form. This means:
1/ integrating with the overall form for schema/validation and temporary persistence
2/ not integrating with the underlying, persisted, indexed, config.
More details:
- persist the query state at the top-level `ResizableWorkspace` like the ingest docs
- update the query request form `ConfigureSearchRequest` to be similar to the ingest docs form, utilizing the `JsonField` component (which handles the auto-formatting as well)
- update `validateAndRunQuery()` to ensure there is a valid, non-empty query, when attempting to click 'Run query' button
- final updates to the formik and schema conversion fns to include the query field
Demo video showing validation, auto-formatting, persistence …

Integrate query into form (not persisted in config)

---

public/pages/workflow_detail/workflow_inputs/input_fields/boolean_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/index.ts
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/utils/config_to_form_utils.ts
public/utils/config_to_template_utils.ts
public/utils/form_to_config_utils.ts

This PR adds the option to skip ingest in the inputs. The selection is persisted in form state and in the indexed `WorkflowConfig`. More details:
- configures a generic `BooleanField` field integrated with formik for rendering and allowing the switching of the boolean form value
- exposes the skip option at the top-level of `WorkflowInputs`, only visible on ingest-side
- updates ingest state if skip is selected by hiding the rest of the input form
- updates the button state at the bottom of the input form when ingest is skipped or not skipped
- updates conversion fns between form / template / ui config to handle the boolean field. additionally, removes ingest-related template nodes (create ingest pipeline, create index) if disabled. This would leave the user with (at most) a single search …

Support skipping ingest in `WorkflowInputs`

---

package.json
public/pages/workflow_detail/workflow_inputs/export_options/export_options.tsx
public/pages/workflow_detail/workflow_inputs/export_options/index.ts
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
yarn.lock

This PR adds the basic export step in the workflow editor. Specifically:
- adds a third step in `WorkflowInputs` and corresponding state to show a third export step, and updates buttons
- adds `ExportOptions` component with the ability to choose different output formats. Currently the backend supports JSON and YAML ([ref](https://opensearch.org/docs/latest/automating-configurations/workflow-templates/)), so we can support those here as well. Final functionality and UX flows are TBD - currently just displaying the formatted template within the editor and the ability to copy it to clipboard. The "Export" button is a placeholder for now
- adds MIT-licensed [js-yaml](https://www.npmjs.com/package/js-yaml) for its lightweight conversion utilities and to produce the final yaml template.
Demo …

Add export step

---

public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/ingest_inputs.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx

This PR achieves 2 small things:
1. Adds an invalid workflow state (layout/wording TBD). When a workflow doesn't have proper ui_metadata configured, shows some descriptive text and the current template of the workflow to provide some utility & visibility.
2. Adds a FilePicker to select any local JSON file (limited to `.json` files only for now), and when loaded, populates the input form with its contents. Further guardrails, different filetypes, etc. have not been finalized.
Demo showing the invalid state and the filepicker, and loading in a file `test.json` that contains the simple json `{ "hello": "world" }`
[screen-capture (47).webm](https://github.com/opensearch-project/dashboards-flow-framework/assets/62119629/1ca82ded-c05f-401c-8434-472e972649ea)
By submitting …

Add invalid workflow state; support JSON doc uploads

---

public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/utils/utils.ts

This PR finalizes all create and edit states for the ingest flow configuration. Specifically:
- updates buttons to be consistent, and be enabled/disabled based on the form and edit state
- updates edit flow to have a 'Delete resources' button, which opens a confirmation modal to confirm deletion. if deletion is selected, revert to the create state, but defaulted to the 'skip' option.
- updates search flow to have a dynamic index configuration; if ingest is configured, enforce the search flow is against the configured index. if ingest is not configured/skipped, then provide a dropdown listing out available indices the user can select to run the search flow against
Demo video showing the create and edit states, new buttons, resource deletion confirmation, and the 2 different states of the …

Finalize edit flow for ingest inputs

---

public/pages/workflows/new_workflow/use_case.tsx

This PR tunes the creation flow slightly to allow setting a custom name on workflow creation from the new workflow page. Also changes the default button text in the cards to `Go`. Defaults the workflow name to the same as before. Also has validation that the name cannot be empty.
Demo video showing the new flow and validation:
[screen-capture (49).webm](https://github.com/opensearch-project/dashboards-flow-framework/assets/62119629/17889c20-ec29-4bb9-9126-6f0104738785)
Makes progress on #66 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING. …

Add name confirmation modal on create

---

common/interfaces.ts
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflows/import_workflow/import_workflow_modal.tsx
public/pages/workflows/import_workflow/index.ts
public/pages/workflows/workflow_list/workflow_list.tsx
public/pages/workflows/workflows.tsx
public/utils/utils.ts

This PR adds support for importing locally saved workflow templates in JSON or YAML format. A new button is available on the base workflows page, for both the workflows list and the new workflow tabs. When clicked, opens up a modal where users can drag-and-drop or import a template from their local filesystem. The modal will validated and prevent or allow importing, depending on 3 different states:
1. Valid UI template (containing the required workflow fields, + containing `ui_metadata` field). No warnings, and users can import. _Note if this is manually done / misconfigured this may still fail; it is up to the user to not corrupt the values within `ui_metadata`_.
2. Valid template (containing the required workflow fields, but not containing `ui_metadata`). Warns that the workflow can be …

Support importing local workflow templates

---

common/interfaces.ts
public/pages/workflow_detail/tools/errors/errors.tsx
public/pages/workflow_detail/tools/tools.tsx
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/workflows.tsx
public/store/reducers/opensearch_reducer.ts
public/store/reducers/workflows_reducer.ts
public/utils/config_to_template_utils.ts
server/routes/flow_framework_routes_service.ts
server/routes/helpers.ts

This PR consolidates some of the error handling and finishes the `Errors` tab in the `Tools` component. `Tools` will automatically switch to the `Errors` tab if any of the following occur:
- error while performing the ingest/query OpenSearch APIs executing when testing ingest/search
- error while performing CRUD APIs on a workflow (create/update/provision/deprovision)
- underlying API error when performing provision/deprovision <-- these are special cases where the REST call returns success, but the `error` field within the workflow state will be populated if some intermediate step may have failed (e.g., index already exists when provisioning, error creating ingest pipeline, etc.)
To handle the last case, we need to persist the error found in redux store, similar to the workflow state. …

Add error field to workflow; propagate all runtime errors in tools tab

---

public/component_types/other/query/index.ts
public/component_types/other/query/query.tsx
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/store/reducers/form_reducer.ts
public/store/reducers/index.ts
public/store/store.ts
public/utils/config_to_workspace_utils.ts

This PR handles some form edge cases and a few other minor changes:
- prevents going to ingest form if unsaved changes on search form
- adds warning on ingest form if there are provisioned search resources, and user is updating the ingest form
- updates query block in workspace to be generic instead of hardcoded to neural query
- rename workspace reducer -> form reducer
- removes ingest doc changes from changing the form state; this is to prevent duplicate ingest and accidental override of existing ingested doc(s)
Screenshot of new callout:
Screenshot of back button available when no unsaved search form changes:
Screenshot of back button unavailable when unsaved search form changes:
By submitting this pull request, I confirm that my contribution is made under the …

Minor form updates

---

public/pages/workflow_detail/workflow_inputs/input_fields/map_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/model_field.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/route_service.ts
public/store/reducers/workflows_reducer.ts
public/utils/utils.ts
server/cluster/flow_framework_plugin.ts
server/routes/flow_framework_routes_service.ts

This PR integrates with 2 new enhancements to Flow Framework APIs:
1. Ability to force delete indices when deprovisioning https://github.com/opensearch-project/flow-framework/pull/763
2. Ability to update certain fields (e.g., `ui_metadata`, `name`) on a provisioned workflow https://github.com/opensearch-project/flow-framework/pull/757
With enhancement 1, we no longer have errors when deprovisioning / reprovisioning a workflow when the index config does not change. Before, this would produce exceptions on provision, due to the fact the index still exists, due to the fact we couldn't delete the index.
With enhancement 2, we can easily update and persist the UI form configuration (stored via `ui_metadata` field) without users explicitly clicking on an Ingest/Search button, which was doing …

Integrate with updated Flow Framework APIs

---

common/constants.ts
package.json
public/pages/workflow_detail/workflow_inputs/config_field_list.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/map_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/utils/utils.ts
yarn.lock

This PR completes the end-to-end flow of input transforms on the ingest side, by way of adding JSONPath parsing support within the ML inference input map configs. More specifically:
- adds MIT-licensed JSONPath (base [JS](https://www.npmjs.com/package/jsonpath) and [TS](https://www.npmjs.com/search?q=%40types%2Fjsonpath)) packages to the plugin
- finishes base functionality of `InputTransformModal` - adds the map form field within the modal, completes generation logic of the output JSON after applying JSONPath and/or dot notation to the specified inputs in the map. Note the logic used here is the same as the ML inference processor logic, when parsing the map config. If no `$.` JSONPath base object selector is specified, it defaults to using dot notation. We do the same logic to produce …

Integrate with JSONPath; complete input transform (ingest)

---

common/constants.ts
common/interfaces.ts
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/json_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflows/new_workflow/utils.ts
public/utils/config_to_form_utils.ts
public/utils/form_to_config_utils.ts

Naturally, the JSON schema of both the sample documents and the query have downstream impact on the ingest and search pipelines, respectively. To help prevent accidental changes, and to make the user make a more explicit choice when editing such fields, this moves those inputs into modals. Users have a readonly view of the values, but must click on an explicit 'Edit' to change the values.
More specifics:
- adds modals to `SourceData` (ingest) and `ConfigureSearchRequest` (search) components, and moves the form configuration inside such modals. Readonly codeblocks are added to the base form page for users to see the current values
- updates the search request to be formally integrated into the form and UI config. It is now consistent with other JSON form values, like index mappings and …

Add guardrails to doc and query JSON inputs

---

public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/output_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processors_list.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/search_inputs.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/utils/form_to_pipeline_utils.ts
public/utils/utils.ts

This PR completes the advanced output transform flow on the ingest side. Specifically:
- fully implements `OutputTransformModal` and the logic for fetching the input and generating the output. The notable difference is on fetching the input - for transforming the output, we run the simulate ingest pipeline API up to and including the currently-configured processor, but also removing any currently-configured output transforms. That way, we get a consistent and expected input to the output transform every time. _It's also possible we refactor both of these modals into a single generic one - since the UI is not finalized, we wait to handle that_
- refactors some logic and helper fns into `utils` to reuse in the input / output transform modals
- refactors and cleans up the form in …

Complete advanced output transform (ingest)

---

common/interfaces.ts
public/configs/ml_processor.ts
public/pages/workflow_detail/workflow_inputs/input_fields/index.ts
public/pages/workflow_detail/workflow_inputs/input_fields/map_array_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/map_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/output_transform_modal.tsx
public/utils/config_to_form_utils.ts
public/utils/config_to_schema_utils.ts
public/utils/config_to_template_utils.ts
public/utils/utils.ts

This PR expands the form inputs for the input map / output map fields for ML processors, to be a _list_ of maps, instead of a single map. This is so multiple predict/inference calls can happen within a single processor's execution. At a high level, this means changing the form, schema, and components to maintain an arr of maps instead of a single one.
Additionally, In the advanced transform modals, users can now select which predict/inference call they want to test out and see test transformation results of.
More specific details:
- add new `mapArray` config field type
- add new `MapArrayField` which takes in a `Formik`'s arr field and maintains an arr of individual `MapField`s
- update the transform modals to maintain a specific map/prediction to test with. Adds in a selector for users …

Support multiple input/output maps for ML processors

---

common/interfaces.ts
public/pages/workflow_detail/workflow_inputs/processor_inputs/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/output_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processors_list.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/utils/form_to_config_utils.ts
public/utils/form_to_pipeline_utils.ts
server/routes/flow_framework_routes_service.ts
server/routes/helpers.ts
server/routes/ml_routes_service.ts

This PR adds ML processor as options in the context of search request and search response. Additionally, it finishes all of the logic in the input transform / output transform modals to dynamically fetch input / generate output. There are a few places where this preview / advanced transform view is gated:
1. Chaining multiple search request processors - in this case, since we don't have per-processor logging available, we cannot generate the interim transformed request. This is already tracked here: https://github.com/opensearch-project/OpenSearch/issues/14745
2. Advanced output transform for search request processors - we cannot do partial simulation of the search request processor in the context of output transformations, since there is no way to configure a working, simulate-able …

Onboard search req / search resp ML processors

---

.github/workflows/draft-release-notes.yml
opensearch_dashboards.json
package.json

fixed draft_release_notes workflow and Renamed plugin in package.json , opensearch_dashboards.json
Related to https://github.com/opensearch-project/opensearch-build/issues/4851

fixed draft_release_notes workflow and Renamed plugin

---

public/general_components/delete_workflow_modal.tsx
public/general_components/multi_select_filter.tsx
public/pages/workflow_detail/components/header.tsx
public/pages/workflow_detail/workflow_inputs/export_options/export_options.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/boolean_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/json_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/map_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/model_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/text_field.tsx
public/pages/workflow_detail/workflow_inputs/processors_list.tsx
public/pages/workflows/empty_list_message.tsx
public/pages/workflows/new_workflow/new_workflow.tsx
public/pages/workflows/new_workflow/use_case.tsx
public/pages/workflows/workflow_list/workflow_list.tsx

Replace instances of `EuiButton` that don't have an explicit sizing attribute to `EuiSmallButton*`.
Replace instances of `Eui<form elements>` that don't have density attributes to `EuiCompressed<form elements>`.

Use smaller and compressed varients of buttons and form components 

---

common/constants.ts
common/interfaces.ts
public/configs/base_config.ts
public/configs/ingest_processors/index.ts
public/configs/ingest_processors/text_chunking_ingest_processor.ts
public/configs/ml_processor.ts
public/configs/sort_processor.ts
public/configs/split_processor.ts
public/pages/workflow_detail/workflow_inputs/config_field_list.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/boolean_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/index.ts
public/pages/workflow_detail/workflow_inputs/input_fields/json_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/number_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/select_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/text_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/text_chunking_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processors_list.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/utils/config_to_form_utils.ts
public/utils/config_to_schema_utils.ts
public/utils/config_to_template_utils.ts
public/utils/config_to_workspace_utils.ts
public/utils/form_to_config_utils.ts
public/utils/utils.ts

This PR enables a pre-configured set of optional parameters for each processor type, all under an `Advanced settings` accordion. It also adds the [text chunking processor](https://opensearch.org/docs/latest/ingest-pipelines/processors/text-chunking) as an available option for ingest.
More details:
- refactors existing optional params and adds a dedicated `optionalFields` field for each processor config
- adds a new text chunking processor (ingest context only). Renders using the specialized `TextChunkingProcessorInputs` due to its complexity; we display a different set of optional fields based on the selected text chunking algorithm. Also adds special logic in `config_to_template_utils` to only add any configured optional fields relevant to the currently selected algorithm.
- adds …

Support optional params for all processors; onboard text_chunking processor

---

common/interfaces.ts
public/pages/workflow_detail/workflow_inputs/processor_inputs/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/output_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/new_workflow/utils.ts
public/route_service.ts
public/store/reducers/workflows_reducer.ts
public/utils/config_to_form_utils.ts
public/utils/config_to_schema_utils.ts
public/utils/config_to_template_utils.ts
public/utils/config_to_workspace_utils.ts
public/utils/form_to_config_utils.ts
server/cluster/flow_framework_plugin.ts
server/routes/flow_framework_routes_service.ts

This PR improves the search flow by allowing fine-grained provisioning (creating a search pipeline and attaching to an existing index) instead of the limitation from before, forcing full index deletion and re-creation. Now data is persisted and can be searched on in the search flow end-to-end. Additionally, cleans up some edge cases and improves the search flow experience overall, making it fully functional end-to-end now.
More details:
- adds `reprovision` parameter on the update workflow API call to support fine-grained provisioning (ref: https://github.com/opensearch-project/flow-framework/pull/804)
- persists several other fields in the UI config, including 1/ ingest pipeline name, 2/ search pipeline name, and 3/ search index name. The pipeline names are created initially & persisted …

Support fine-grained provisioning; handle more edge cases on search flow

---

common/interfaces.ts
public/configs/search_request_processors/ml_search_request_processor.ts
public/pages/workflow_detail/workflow_inputs/config_field_list.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/json_field.tsx
public/utils/config_to_form_utils.ts
public/utils/config_to_schema_utils.ts
public/utils/config_to_template_utils.ts

Adds support for the `query_template` parameter for the ML inference processor in the context of search request. This param is used to rewrite a query, commonly used for creating some knn query based on vectors returned from an embedding model. 
Also cleans up the `ConfigFieldList` to support `json` fields and `jsonString` fields to fully support all optional field types. The latter `jsonString` does not have the JSON validation, as it could be invalid JSON with variable placeholders in the context of a JSON template. Currently, only the added `query_template` field uses this field type.
And lastly, finishes processing of ML processor optional inputs and ensure they are included in the final generated template configuration.
Demo video, showing a semantic search use case. Indexes some …

Support `query_template` optional field for ML search request processor

---

public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/new_workflow/use_case.tsx

Another usability PR to clean up 2 things:
1. improve button enablement/disablement based on redux loading states (representing APIs in-progress), and state vars when a user-specified ingest, search, or delete action occurs
2. Removes unnecessary page reload on workflow creation
Demo video showing simplified creation flow and more fine-grained button states:
[screen-capture (25).webm](https://github.com/user-attachments/assets/661264f8-f479-4255-b8b2-f88a942aa366)
Resolves #287 
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer- …

Improve loading state; prevent duplicate refresh

---

common/constants.ts
common/utils.ts
public/general_components/index.ts
public/pages/workflow_detail/components/export_modal.tsx
public/pages/workflow_detail/components/header.tsx
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/json_field.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/import_workflow/import_workflow_modal.tsx
public/pages/workflows/new_workflow/use_case.tsx
public/pages/workflows/new_workflow/utils.ts
public/pages/workflows/workflow_list/columns.tsx
public/pages/workflows/workflow_list/delete_workflow_modal.tsx
public/pages/workflows/workflow_list/workflow_list.tsx
public/pages/workflows/workflows.tsx
public/utils/config_to_schema_utils.ts
public/utils/utils.ts

This PR covers a bunch of general usability improvements:
- refactors the delete workflow modal into the workflow list module
- updates the delete workflow modal by adding deprovisioning as an option (and setting it as the default) when deleting workflows from the list page
- adds a 'failed to find workflow' dedicated page due to invalid id in url, for example
- adds more loading state and visibility when deleting
- adds input limits - max 1000 documents, max 100 chars for string, max 10000 chars for json string
- adds regexp matching and character limit handling when defining workflow name from the new workflows page
- adds `getCharacterLimitedString()` util fn to dynamically truncate strings if beyond the specified limit and adds an ellipses. Audited the entire plugin to ensure the …

Improve input constraints; general usability improvements

---

common/constants.ts
common/interfaces.ts
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/edit_query_modal.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/import_workflow/import_workflow_modal.tsx
public/pages/workflows/new_workflow/utils.ts
public/pages/workflows/workflow_list/workflow_list.tsx
public/pages/workflows/workflows.tsx
server/resources/templates/hybrid_search.json
server/resources/templates/multimodal_search.json

This PR is a start to improve the user experience for existing, basic neural-search-variation use cases:
1. Onboards hybrid and multimodal use cases as options
2. Provides preset, sample queries for users to use. Currently just basic ones for each use case.
More details:
- sets up and defines constants for some basic queries using the `neural` clause based on different use cases
- refactors the query editing modal into a standalone `EditQueryModal` component to separately handle state
- minor tune to the `Run query` button to allow it to run, even if no search processors are defined
- basic preset UI config logic in `new_workflow/utils` for the new use cases, including setting the default query
- adds filters for the new use case types in the workflow list page
Notes:
- the hybrid query …

Add basic preset queries; onboard hybrid/multimodal search use cases

---

common/constants.ts
public/pages/workflow_detail/workflow_inputs/input_fields/map_array_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/map_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/output_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/edit_query_modal.tsx

This PR improves the form inputs in 2 places:
1. Hides the multi-prediction feature unless the user explicitly wants to. In general, a single prediction configuration in the ML processors are sufficient.
2. Changes the preset query selector from a super select, to a popover button. This is so we don't persist state after users begin editing/updating the query. For example, a user could select "semantic search" preset, edit it, and before, the dropdown would still show "semantic search", even if the query had been changed entirely to something else. The new flow is a stateless button to select from a starting preset, and nothing more
More details:
- adds states in `MapArrayField` to dynamically render based on if there is 0 maps, a single map, a single map with no entries, and multiple …

General form improvements

---

common/constants.ts
common/interfaces.ts
public/pages/workflow_detail/workflow_inputs/search_inputs/edit_query_modal.tsx
public/pages/workflows/new_workflow/new_workflow.tsx
public/pages/workflows/new_workflow/quick_configure_inputs.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/pages/workflows/new_workflow/use_case.tsx

This is a continuation of the usability improvements. Specifically, this PR adds several standard quick-config fields to common use cases that users can optionally populate, before entering the advanced editor view. When populated, the values are then propagated into the workflow config in various places. Details below.
Implementation details:
- adds a `QuickConfigureFields` type containing a set of optional fields
- adds a `QuickConfigureInputs` component, that dynamically renders form fields based on the use case. For example, a custom/blank use case, vs. a semantic search use case, vs other advanced / hybrid search / neural sparse search / future use cases, will have different inputs exposed. Current implementation shows the same fields available to semantic/multimodal/hybrid; this …

Add quick-create fields in the create flow and form pre-population

---

common/constants.ts
public/configs/search_response_processors/index.ts
public/configs/search_response_processors/normalization_processor.ts
public/pages/workflow_detail/workflow_inputs/processor_inputs/normalization_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processors_list.tsx
public/pages/workflows/new_workflow/quick_configure_inputs.tsx
public/utils/config_to_template_utils.ts

Adds the normalization search phase results processor under the "Enhance search results" section on the form. Under the hood, this processor runs in between the query and fetch phases. We abstract out those details on the UI.
More details
- adds new `NormalizationProcessor` config class to persist its parameters, all of which are optional
- adds a dedicated `NormalizationProcessorInputs` component instead of defaulting to the `ConfigFieldList`. The reason for this, is we want to have special form logic for inputting the weight parameters. As mentioned in the code comment, we can expand this to potentially link the weights to the configured query, enforce the length, etc. For now, just add some helper text and a link to the documentation
- adds special parsing logic on …

Onboard normalization processor

---

public/render_app.tsx

- #### Resolved the following issue: 
When 'Search Studio' is selected from the SideNav on the 'workflow detail' page, the page was not redirecting to the 'workflows' page.
- #### Below screen Recording shows the issue that I am trying to resolve.
[screen-capture (15).webm](https://github.com/user-attachments/assets/a297076f-bf97-44c1-92a2-49fb08a41bec)
- The [dashboards-flow-framework](https://github.com/opensearch-project/dashboards-flow-framework) uses a hash router. To ensure proper redirection, the hash has been added at the end of the URL.
- #### Issue Resolved here and can be seen in below screen recording. 
[screen-capture (16).webm](https://github.com/user-attachments/assets/95147dd1-acae-479a-a3ee-9277ac3916e9)
By submitting this pull request, I confirm that my contribution is …

Refine 'Search Studio' URL handling in Side Nav with NewHomePage enabled

---

public/pages/workflow_detail/workflow_inputs/input_fields/map_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/text_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/output_transform_modal.tsx
public/pages/workflows/new_workflow/quick_configure_inputs.tsx

Small PR to make a few things consistent:
1. The sample input in the input and output transform modals. Now, all scenarios will display a single input out of the array of results. This is to prevent over-using ML inference calls, and to be consistent with the produced output transform, which is only outputting a single value by default. Adds helper text in the modals as well.
2. The text fields in the input/output transforms do not stretch by default, but the select option does (select option shows up when there is a model interface and a preset list of available input/output fields)
Screenshot of modal:
N/A
For more information on following Developer Certificate of Origin …

Minor consistency fixes

---

common/constants.ts
common/interfaces.ts
public/pages/workflows/new_workflow/quick_configure_inputs.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/pages/workflows/new_workflow/utils.ts
server/resources/templates/hybrid_search.json
server/resources/templates/multimodal_search.json
server/resources/templates/semantic_search.json

Improves the presets for the OOTB use cases:
- adds more preset queries
- sets a default ML search response processor for semantic/hybrid/MM
- improves default queries for semantic/hybrid/MM
- adds a quick-configure image field for MM
- tunes descriptions for semantic/hybrid/MM
N/A

Improve presets for use cases

---

common/constants.ts
public/pages/workflow_detail/workflow_inputs/input_fields/select_with_custom_options.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/pages/workflows/new_workflow/utils.ts
public/utils/utils.ts

This PR adds a handful of usability improvements:
1.  allows the query template fields in the ML search request processors to be automatically populated
2. adds random name generation for index creation to prevent the easy case of name clashing when creating multiple workflows
3. sets default values for the select dropdowns (automatic population of the input maps when using a model with an interface)
Demo video showing that when all quick-config fields are filled out, and when using a model with an interface, ingest & search can be fully working by only configuring:
1/ passing in sample documents to ingest, and
2/ the query and input map for the search request processor (this may further be automated in the near future) …

More preset automation & usability improvements

---

public/pages/workflows/import_workflow/import_workflow_modal.test.tsx
public/pages/workflows/new_workflow/new_workflow.test.tsx
public/pages/workflows/workflow_list/workflow_list.test.tsx

Adding unit tests for new_workflow, workflow_list, import_workflow_modal components
Related to #96 , #97 

Adding unit tests for new_workflow, workflow_list, import_workflow_modal components

---

public/pages/workflows/new_workflow/quick_configure_inputs.tsx
public/pages/workflows/new_workflow/utils.ts

This PR sets default values for the majority of the quick-configure fields when creating workflows from a preset.
N/A

Add presets for quick config fields

---

common/constants.ts
public/app.tsx
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflows/workflows.tsx
public/plugin.ts
public/render_app.tsx
public/utils/constants.ts

Renames all of the visible titles of the plugin on the UI, including the plugin name in the OSD side nav bar, the url paths, and the breadcrumbs. Also minor cleanup to add constants and some consistency.
Screenshots of changes:
N/A

Rename visible plugin name to Search Studio

---

common/constants.ts
common/interfaces.ts
public/pages/workflow_detail/workflow_inputs/input_fields/map_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/model_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/select_with_custom_options.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/new_workflow/new_workflow.tsx
public/pages/workflows/new_workflow/quick_configure_inputs.tsx
public/route_service.ts
public/store/reducers/index.ts
public/store/reducers/ml_reducer.ts
public/store/store.ts
server/cluster/ml_plugin.ts
server/routes/helpers.ts
server/routes/ml_routes_service.ts

This PR adds a set of constants for common embedding models from popular remote services. If a model name is found in the connector blueprint, and it is a model that we persist a constant for, we prefill the dimensions with the known value.
More details:
- onboards the search connectors API to fetch connector details (in this case, any specified 'model' name found)
- adds dimensions constants for OpenAI and Cohere popular embedding models
- adds basic Connector-based interfaces
- adds a hook in `QuickConfigureInputs` to try to derive the `dimensions` when a model is selected. this is done by traversing to the associated connector ID, extracting out the details, and looking for the model name
- minor tuning of the select dropdown in the maps 
Demo video, showing the "Embedding length" …

Prefill dimension if known remote model found; onboard search connectors API

---

common/constants.ts
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/map_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/select_with_custom_options.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/output_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processors_list.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/utils/utils.ts

PR to clean up and simplify some of the forms for configuring processors, and some other minor improvements. Specifically:
- wraps the processor forms in an accordion. They are all set to be closed by default, except when adding a new one inline, in which case defaults to being open to have less friction for starting to edit/config the newly added processor
- passes model interface instead of the derived model inputs/outputs as much to simplify the amount of state components, and set it up for downstream validation (to be added in a later PR)
- adds parsing logic in `QuickConfigureModal` to derive default key/value pairs in the input / output maps based on any model interface, if applicable. Adds flexibility and default support for multiple input/output fields, compared to 1, before.
- …

Improve and simplify processor form configs

---

common/interfaces.ts
public/pages/workflow_detail/workflow_inputs/processor_inputs/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/output_transform_modal.tsx
public/utils/utils.ts

Adds more details and validation feedback in the transform modals. Specifically:
- for both input/output modals: remove the "generate" button and automatically generate the transforms if there is enough valid inputs to do it
- for input modal: add a "View model inputs" button at the bottom to fetch the model's input interface (if applicable). Opens up a popover with the JSON details
- for input modal: adds a validation icon indicating success/failure based on the generated output meeting the JSON schema requirements as defined by the model interface (if applicable)
Demo video below, using the example model with configured model interface. The UI indicates validation success or failure when there are correct and incorrect schemas produced by the input maps.
```
POST …
```

Integrate model interface info in advanced transform modals

---

public/configs/search_response_processors/ml_search_response_processor.ts
public/pages/workflow_detail/workflow_inputs/config_field_list.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/model_field.tsx

Onboards the added `one_to_one` configuration specifically for ML search response processors. For backend implementation, see https://github.com/opensearch-project/ml-commons/pull/2801.
- adds optional field to the response processor config
- minor bug fixes to the boolean form fields (there is issues with the `EuiRadioGroup` when duplicate option IDs visible on the DOM)
- minor bug fix to not display a "missing model interface" callout until a model is selected
Demo video, showing a model that is expecting a string input. When `one_to_one` is `false`, it fails, as the ML search resp processor collects all of the results into an array before sending to the model. When switching to `true`, it succeeds, since it treats each resp document as a standalone inference call, and does not nest in …

Onboard one-to-one config for ML search resp processors

---

common/constants.ts
common/interfaces.ts
common/utils.ts
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/ingest_inputs.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/select_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/output_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/new_workflow/utils.ts
public/route_service.ts
public/store/reducers/opensearch_reducer.ts
server/routes/opensearch_routes_service.ts

This PR adds a third option to specify the source data - from an existing index. When selected, x number of documents are automatically fetched and populated. Additionally, when data is fetched from an existing index (or from an uploaded document, attempt to prefill some config data. More specifically:
- if index data is automatically populated, 1/ clear and update ML ingest processors (if applicable) with new text/vector fields (image is ignored for now, as we don't have a clear default pattern in ML processors for this use case. Additionally, would increase the level of fine-grained assumptions we already make)
- if uploaded document data is automatically populated, clear some fields in the ML ingest processors (if applicable)
Additional improvements:
- cleans up remaining stringify …

Add existing indices as a source data option; improve config autofilling

---

common/constants.ts
package.json
public/pages/workflow_detail/workflow_detail.test.tsx
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/map_array_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/map_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/select_with_custom_options.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/output_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/search_inputs.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/store/reducers/ml_reducer.ts
public/store/reducers/opensearch_reducer.ts
public/store/reducers/presets_reducer.ts
public/store/reducers/workflows_reducer.ts
test/utils.ts
yarn.lock

This PR adds functionality to dynamically fetch a list of options when configuring input / output maps for ML processors. Specifically, adds support for 3 scenarios:
1. List of document fields as values for input maps when the document form field is populated (ingest)
2. List of query fields as values for input maps when the query form is populated (search)
3. List of document fields as values for input maps when configuring ML search response processors. References the selected index's mappings to populate options, including the field mapping type.
Note the dropdown still allows custom options if users need (e.g., pulling out a single value from an array, aggregation via JSONPath, etc.).
More details
- adds `docFields`/`queryFields`/`indexMappingFields` as state vars in …

Fetch default options for ML processor config maps

---

public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx

This PR reverts the autosave functionality due to its ambiguity on when cluster resources are updated. To handle saving, this adds an explicit save button, and corresponding undo, to revert to the last saved state. Buttons are enabled/disabled based on the form state. Under the hood, when users click save, it runs the update workflow API with `reprovision=false`. Only the config is saved, but not the underlying workflow template or any associated resources. For full updates, users still have the ingest/search buttons. Updated text to more explicitly state what is happening when those are executed, which is actually building out the resources and running ingest/search. When users click the revert button, the form and transient UI config is reverted to the saved/indexed config.
Details on …

Add explicit save / revert buttons in search & ingest forms

---

common/constants.ts
common/interfaces.ts
public/configs/search_response_processors/collapse_processor.ts
public/configs/search_response_processors/index.ts
public/general_components/general-component-styles.scss
public/pages/workflow_detail/tools/tools.tsx
public/pages/workflow_detail/workflow_detail.test.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processors_list.tsx
public/pages/workflows/new_workflow/quick_configure_inputs.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/pages/workflows/new_workflow/utils.ts
public/utils/config_to_template_utils.ts
server/resources/templates/rag.json

Adds a basic RAG preset to the library. Pre-populates:
- ML search response processor with an LLM to generate results (defaults to many-to-one)
- `collapse` response processor to only return unique ML responses (in many-to-one case, this will be one result)
More details:
- onboards `collapse` search response processor
- adds an `llmResponse` quick-config field, and default quick-config field values for the new RAG usecase
- fixes bug of input transform fetching failing on search response processors when no prior search request or search response processors
- refactors helper fns in `QuickConfigureModal` and makes them more generic
Notes:
- future PRs will improve the prompt template editing experience. For now, it is entirely free-form.
- future PRs will improve the checking of …

Onboard basic RAG preset

---

common/interfaces.ts
public/pages/workflow_detail/workflow_inputs/input_fields/boolean_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/output_transform_modal.tsx
public/utils/utils.ts
server/routes/helpers.ts

This PR standardizes the generated source input to consistently match exactly the way the ML processors will transform the inputs. For `full_response_path=false/true`, both are displayed exactly how the ML processor will parse it. The one caveat is, there is still work to be done on the search response side to handle many-to-one/one-to-one toggling better.
Also has other small fixes:
- handles when input or output is missing from the model interface (both are not required)
- handles empty search pipeline edge case when simulating source output
- triggers `touched` when toggling boolean field - before, changing these values was not triggering save to be available.
- removes the invalid check of bracket notation not available for the input/output map configurations
- adds loading logic when …

Standardize source data to input/output transform modals

---

public/pages/workflow_detail/workflow_inputs/processor_inputs/output_transform_modal.tsx

Recent bug fix enabled testing of the ML response processor output transforms: https://github.com/opensearch-project/ml-commons/pull/2944
As a result, there was a single parsing issue. This is a one-line fix to fix that. Also sets defaults for if `inference_results` is undefined, don't display `undefined` as a value.
Demo video:
[screen-capture (20).webm](https://github.com/user-attachments/assets/9ced6de6-7786-4837-a434-00c069f0ab78)

Fix parsing of ML response processor

---

public/configs/ml_processor.ts
public/configs/search_response_processors/collapse_processor.ts
public/configs/search_response_processors/normalization_processor.ts
public/pages/workflow_detail/tools/ingest/ingest.tsx
public/pages/workflow_detail/tools/query/query.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/json_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/output_transform_modal.tsx
public/pages/workflow_detail/workspace/workspace.tsx

For RAG use cases, users may want to configure the prompt templates directly in the ML processors, dynamically using data inputs as part of the prompt. For example, collecting a list of documents as context to pass to an LLM to summarize and return a human-readable response.
This PR adds a component in the input transform modal to view the original prompt template, and the prompt template with any injected input values (if applicable).
More details:
- adds prompt-related state vars and custom hooks when a prompt and/or input parameters are populated in `InputTransformModal`
- dynamically renders the new components if a valid `prompt` field is found in the processor's `model_config` field
- allows toggling between showing the prompt or not
- allows toggling between showing the original …

Add optional prompt template transformation in input transform

---

common/constants.ts
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/output_transform_modal.tsx
public/utils/utils.ts

ML inference processors parse out the response differently depending on if `full_response_path` is true or not. The model interfaces will always include the full path. To help abstract this on the UI, we can implement the same parsing logic to get to the nested model output data when `full_response_path=false`. This way, it is consistent across the interface, and the configured output map configuration. The path to get such nested data is `inference_results[0].output[0].dataAsMap`.
More details:
- only displays preset options for model outputs when `full_response_path=false`. Else, it will not be useful, as the path would always start with `inference_results` arr, and users would need to write full JSON path here to get to the nested data they want
- adds a "View output schema" button …

Set default outputs and display schema based on `full_response_path`

---

common/constants.ts
common/utils.ts
public/configs/search_response_processors/ml_search_response_processor.ts
public/pages/workflow_detail/workflow_inputs/processor_inputs/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/output_transform_modal.tsx
public/utils/utils.ts

This PR adds specific, relevant forms to be exposed in the advanced transform modals, such that users can toggle and test directly within the modal, instead of navigating to/from the advanced settings fields. Specifically:
- exposes `one_to_one` toggling on INPUT transform for SEARCH RESPONSE only. This changes what the source input will be (single value vs. array of values)
- exposes `full_response_path` toggling on OUTPUT transforms for INGEST / SEARCH RESPONSE only. This changes what the source output will be (nested model response vs. full model response)
More details
- adds visual support for the default many-to-one behavior on input transform (when `one_to_one` is false). In this scenario, we collapse the values from all of the documents into a single list, to pass as a single …

Support relevant form toggling in advanced transform modals

---

common/constants.ts
common/interfaces.ts
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/configure_prompt_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/index.ts
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/output_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/edit_query_modal.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx

Adds a dedicated section and modal for optionally configuring a prompt. Only exposing in the search response context, as that is the most likely place users will be setting it up. Can easily be enabled for other contexts if wanted later on. The dedicated modal has 3 main parts: 1/ dropdown with prompt template presets for users to select from, 2/ the user-editable text editor that displays the prompt, and 3/ the list of model inputs (and corresponding placeholder strings) that users can copy/paste, in order to insert these dynamic values into the template at runtime (this part is omitted if no input interface found). A common example of this, is passing returned documents as context in the prompt template for some LLM to answer a question with / summarize/ etc.
Implementation details:
- …

Add dedicated prompt configuration for ML search resp processors

---

public/pages/workflow_detail/workflow_detail.test.tsx
public/pages/workflows/import_workflow/import_workflow_modal.test.tsx
public/pages/workflows/import_workflow/import_workflow_modal.tsx
public/pages/workflows/new_workflow/new_workflow.test.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/pages/workflows/new_workflow/use_case.tsx
public/pages/workflows/workflow_list/delete_workflow_modal.tsx
public/pages/workflows/workflow_list/workflow_list.test.tsx
public/pages/workflows/workflows.test.tsx
public/pages/workflows/workflows.tsx
test/interfaces.ts
test/utils.ts

- Expanded functionality tests for the New Workflow and Workflow List components.
- In the Workflow List component, tested sorting, pagination, delete actions, and view resources.
- In the New Workflow page, tested templates and quick configuration.
- Will raise a follow-up PR to test the search bar in both of the above-mentioned components.

Expanded functionality tests for New Workflow and Workflow List components.

---

public/pages/workflow_detail/workflow_detail.test.tsx
public/pages/workflow_detail/workflow_inputs/processors_list.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/edit_query_modal.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/new_workflow/new_workflow.test.tsx
public/pages/workflows/workflow_list/workflow_list.test.tsx
public/pages/workflows/workflows.test.tsx

- Added test cases for the search bar functionality in the Workflow List page and New Workflow page.
- Included additional test cases to improve the test coverage for the Workflow Details page.
related to #95 
closes #98
closes #100 

Expanded unit test coverage for key UI components

---

.github/workflows/build-and-test.yml
codecov.yml

- Add Codecov for test coverage reporting.
Related to #109

Add Codecov for test coverage reporting

---

common/constants.ts
common/interfaces.ts
public/pages/workflow_detail/tools/tools.tsx
public/pages/workflow_detail/workflow_detail.test.tsx
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/configure_prompt_modal.tsx
public/utils/utils.ts
server/routes/helpers.ts

Misc improvements PR:
- improves the logic on when to expose the "Configure prompt" section in the ML processor configs. Rather than exposing by default for ML search response processors, instead only expose if there is a present 'prompt` parameters via the connector blueprint, regardless of context (ingest,search req, search resp). In general, this will require some consistency on the expected blueprints to contain such field for such use cases - ongoing discussions with ML team to sort this part out.
- supports / is consistent with the bug fix in ML ingest processors, (see [here](https://github.com/opensearch-project/ml-commons/pull/2985))such that we do not always default to an array obj. Updates the underlying `jsonpath` call from `query` -> `value`, where `value` returns the first …

Improve prompt config UX; support JSONPath bug fix

---

public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/configure_prompt_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/override_query_modal.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx

This PR improves the UX for query configuration/overriding the query via a `query_template` field exposed in the ML search request processors. This is a common pattern for vector search use cases, to generate a valid knn query, injecting the returned vector embedding directly into the new query. Before, this was nested under 'Advanced settings', under 'Query template'. Now, we add a dedicated modal similar to prompt-building for this particular scenario.
More details
- adds a 'Override query' option for ML search req processors only
- supports preset selection, the same as the base query configuration (one difference, is once a preset is selected, we sanitize to be in a proper templated format, since the value here is a _template_ rather than a _string_)
- similar to the prompt modal, we …

Add dedicated UX for query template building (ML search req processors)

---

.github/workflows/backport.yml

Bumps the github action to fix the failing DCO checks on automated backport PRs.
Resolves #399 

Bump VachaShah/backport to v2.2.0

---

.github/workflows/backport.yml
public/pages/workflows/workflows.tsx

The active tab update does not occur when clicking the "create workflow" button from the list page. This fixes that.
Also fixes the backport args reqd with the new version of the backport action in the workflow.
Resolves #414 
Resolves #415 

Fix URL update for 'Create workflow' button (list page)

---

opensearch_dashboards.json
server/resources/templates/custom.json
server/resources/templates/hybrid_search.json
server/resources/templates/multimodal_search.json
server/resources/templates/rag.json
server/resources/templates/semantic_search.json
server/resources/templates/sentiment_analysis.json
test/utils.ts

Bumping the version compatibility matrix to have a minimum of 2.18, since our plugin is expected to launch in 2.18, 
closes https://github.com/opensearch-project/dashboards-flow-framework/issues/409

Bumped minimum compatibility to 2.18.0

---

.github/workflows/backport.yml
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/configure_prompt_modal.tsx

Fix placeholder strings in prompt template modal. Before, the copied strings had an unnecessary `/` character which was inconsistent with the defined placeholder syntax.
Also fixes the backport action to be consistent with OSD's: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/.github/workflows/backport.yml

Fix placeholder strings in prompt template modal

---

public/pages/workflow_detail/workflow_inputs/ingest_inputs/ingest_inputs.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/import_workflow/import_workflow_modal.tsx

General PR with a variety of bug fixes and minor UX improvements.
Demo video highlighting changes:
[screen-capture (9).webm](https://github.com/user-attachments/assets/e12a0c97-51e8-4dad-b1c4-ff433d1cc14e)
--

Misc bug fixes and minor UX improvements

---

common/constants.ts
public/general_components/processors_title.tsx
public/pages/workflow_detail/components/header.tsx
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/tools/tools.tsx
public/pages/workflow_detail/workflow_detail.test.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/map_array_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/map_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/output_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processors_list.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx

Continuation of #427 . Changes:
Demo video highlighting changes:
[screen-capture (11).webm](https://github.com/user-attachments/assets/95fa6e01-2e6f-4dcc-afd4-603684f67899)

Misc bug fixes and minor UX improvements II

---

common/constants.ts
public/pages/workflow_detail/components/header.tsx
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/workflow_detail.test.tsx
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
test/utils.ts

Moves the undo & save buttons in the top-level header of the Workflow Details page. In order to do this, a lot of the state scoped within `WorkflowInputs` had to be lifted up the dependency tree, in order to be accessible in the header component, where the buttons were relocated to. The majority of this PR is just refactoring the state and related props to/from the parent/child components.
Other notable changes include:
- adding the save/undo buttons to the `TopNavMenu` so they are visible when `useNewHomePage : true`
- fixing an endless loop bug in the test utils that was throttling the tests. By moving some of this state in `WorkflowDetails`, it actually would timeout and the tests would fail. After optimizing, there is no unnecessary rendering happening
- moves `CONFIG_STEP` as a …

Move undo & save buttons in top-level header

---

common/constants.ts
common/interfaces.ts
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data_modal.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/json_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/model_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/number_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/select_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/select_with_custom_options.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/text_field.tsx
public/utils/config_to_schema_utils.ts

This PR decouples the form state for configuring source data in the "Edit source data" modal. Instead of using the global, parent form, we create a new sub-form to persist interim form state. The parent form is only updated, if a user explicitly clicks "Update", and if there are no validation errors. Following PRs will follow this same pattern for other form-based modals, including input/output transforms, and query editor modals.
Details:
- moved the modal into standalone `SourceDataModal` component. Here, we create a new `Formik` component, and persist some custom hooks etc. within it, so we can listen on changes _only_ to the sub-form values.
- refactors state vars and state handling from `SourceData` -> `SourceDataModal` as much as possible
- add new types for the sub-form
- removes …

Add standalone form state for source data

---

public/app.tsx
public/plugin.ts
public/render_app.tsx

- Removing the SideNav within the flow framework dashboards as discussed in  https://github.com/opensearch-project/dashboards-flow-framework/issues/444
**OldHomePage:**
**NewHomePage:**
closes #444

Removing the SideNav within the flow framework dashboards

---

common/interfaces.ts
public/pages/workflow_detail/workflow_detail.test.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data_modal.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/edit_query_modal.tsx

Add standalone form state for query editing modal. Similar to #445, this PR nests the modal in a `Formik` sub-form. Some temp vars are added to persist state. The parent form value is only updated if the user explicitly clicks "Update" and there are no validation errors.
Demo video:
[screen-capture (10).webm](https://github.com/user-attachments/assets/d09254da-4792-45ec-a9c5-85db7dcc7ada)
Makes progress on #446 

Add standalone form state for query editing modal

---

public/pages/workflow_detail/components/header.tsx
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/tools/tools.tsx
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflow_detail/workspace/workspace-styles.scss
public/pages/workflow_detail/workspace/workspace.tsx

- Reduced padding between panels
- Added border radius to the panels
- Decreased empty space at the bottom below panels. 
- Fixed header as previous workflow title is some part cut at the top.  
- Removed unwanted margins present for panels in  workflow detail page
[screen-capture (25).webm](https://github.com/user-attachments/assets/a6834d3d-da4c-4478-815c-297b554216bb)

Fixed workflow detail page UX bugs

---

common/interfaces.ts
public/pages/workflow_detail/workflow_inputs/input_fields/map_array_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/output_transform_modal.tsx

Continuation of #446. Adds interim form state for the advanced transform modals `InputTransformModal` and `OutputTransformModal`. Changes made within these modals only update the parent form when users explicitly click "Create" and the form is valid. Implementation-wise, follows the same patterns as the previous related PRs. Also cleans up a few unused props passed around between the transform modals and its parent/child components.
TODO:
Demo video, showing all form states for input and output transforms for ingest, search req, and search resp:
[screen-capture (12).webm](https://github.com/user-attachments/assets/ba7ebb0c-a056-4888-a146-28a9f3e9262e)
Makes progress on #446  …

Add standalone form state for advanced transform modals

---

public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/output_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/edit_query_modal.tsx

This PR updates the layout to meet UX guidelines. It moves the transform configuration at the top-level, and combines the source and transformed JSONs below that, but in a side-by-side manner for easier comparison. Changes consistently for the input transform modal and output transform modal. Also adds a few tooltips for descriptions, instead of displaying inline and taking up extra space. Also updates the rest of the form modal footer btns to be consistent.
Empty state callouts and the exposed config (full_response_path, one_to_one) is TBD where that will live in the modal. If UX suggestions, will update in a different PR.
Demo video, showing the input and output states for the 3 different processor contexts (ingest, search req, search resp): …

Refactor subcomponents in advanced transform modals

---

public/pages/workflow_detail/workflow_inputs/input_fields/map_array_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/map_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/output_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processors_list.tsx
public/utils/config_to_template_utils.ts

Updates and refactors several components related to the processor forms.
Specifically:
- wraps each processor accordion in a panel
- wraps the add processor button in a panel
- several ML processor improvements: 1/ autopopulating the model inputs / outputs if there is a defined interface, 2/ swapping the k/v entries for the output map for readability purpose, 3/ making the model inputs/outputs static if there is a defined interface, and 4/ updates to the buttons (add input/output, add input/output group) for consistency with other button changes
- updates the template conversion helper fn. Since we swap the keys/values for the output map in the form, we need to swap back when creating the underlying processor config.
Demo video showcasing the form updates: …

Refactor processor form components

---

public/pages/workflow_detail/workflow_detail.test.tsx
public/pages/workflow_detail/workflow_inputs/config_field_list.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/boolean_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/output_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx

- Moves the exposed configs (one_to_one for input transforms of search response processors, full_response_path for output transforms of ingest and search response processors) into a dedicated "Advanced settings" accordion under "Define transform" subsection of the modals.
- Updates the `BooleanField` implementation to be more compact, using a checkbox instead of radio group. Moves any helper text under an `IconTip`.
Demo video, showing the new checkbox form components, and the new advanced settings accordions and configs in the input/output transform modals for the different processors.
[screen-capture (16).webm](https://github.com/user-attachments/assets/5777b8f5-c02c-4496-b9d5-ec224cac3ccf)
By submitting this pull request, I confirm that my contribution is made under the terms of the …

Move exposed configs in the advanced transform modals

---

public/pages/workflow_detail/components/header.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx

Use browser-native popups to warn users of unsaved changes when refreshing. Adds a basic hook to add/remove event listeners when the component is unloaded (triggered on refresh), and if `saveDisabled` is `false`, indicating there are unsaved changes.
Makes progress on #469 

Warn users on browser refresh if unsaved changes

---

common/constants.ts
public/configs/search_response_processors/index.ts
public/configs/search_response_processors/rerank_processor.ts
public/pages/workflow_detail/workflow_inputs/processors_list.tsx
public/utils/config_to_template_utils.ts
public/utils/config_to_workspace_utils.ts

Onboards the rerank search response processor ([by_field](https://opensearch.org/docs/latest/search-plugins/search-pipelines/rerank-processor#the-by_field-rerank-type) type only). This can be used in conjunction with a reranking model, to re-sort the returned documents by the model's scores, instead of the default BM25 `_score`.
Demo video, showing the basic re-sorting by `review` field instead of `_score`.
[screen-capture (2).webm](https://github.com/user-attachments/assets/014d3bc8-549f-44f9-ae72-aef6c78fdac6) …

Onboard rerank by field processor

---

common/constants.ts
public/pages/workflow_detail/workflow_inputs/input_fields/map_array_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/map_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/output_transform_modal.tsx
public/utils/utils.ts

This PR improves 2 parts:
1. JSONPath handling - removes special logic for array parsing, as there is some other ongoing discrepancies which will be resolved in #478 
2. Tooltip wording & placement improvements in the input & output transforms to be more guided for users.

JSONPath bug fix & improved wording in input/output transforms

---

common/constants.ts
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/output_transform_modal.tsx
public/utils/config_to_template_utils.ts
public/utils/utils.ts

This PR improves the path parsing and JSONPath handling when configuring advanced transforms in the ML processors. Added detailed comments in the source code for readability.
- improves `generateTransform` to handle more edge cases and be consistent without the backend handles path parsing for the different scenarios (input vs. output, ingest vs. search request vs. search response).
- adds new`sanitizeJSONPath()` fn used in 2 places: 1/ when auto-populating keys for the query or document JSONs (ensures they will run consistently on frontend & backend), and 2/ when converting to a template (to ensure it runs properly on the backend).
- adds new fn `isIndefiniteJsonPath()` to help make the return values of a JSONPath execution consistent. Note: this is not a full-featured fn. The frontend …

Improve consistency of JSONPath parsing & execution across frontend/backend

---

public/pages/workflow_detail/tools/errors/errors.tsx
public/pages/workflow_detail/tools/resources/resources.tsx
public/pages/workflow_detail/workflow_detail.test.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/configure_prompt_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/output_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/override_query_modal.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/edit_query_modal.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflow_detail/workspace/workspace.tsx

Continuation of #432, #427
- adds NPE checks on response parsing of APIs when running ingest/search
- add button icons for dropdowns and form navigation
- change the button group for toggling between JSON / visual views on the Workspace
- change the empty resources prompt
- change the empty errors prompt

Misc bug fixes and minor UX improvements III

---

public/pages/workflow_detail/components/header.tsx

Show experimental badge on Workflow Details page (new and old).
Screenshot (new)
Screenshot (old):
Screenshot (old, popover opened):
Makes progress on #461 

Show experimental badge on Workflow Details page (new and old)

---

common/constants.ts
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/input_transform_modal.tsx
public/utils/utils.ts

The request can be accessed in the ML search response processors via `_request`. This can be useful for rerank use cases, which may want to tie in original query context info, with returned documents, to generate reranked scores.
This PR adds some helper tooltip text on how to add, and updates the transform logic to handle this special case.
Example below demonstrates a rerank use case using Cohere ReRank English V3. The original query text is combined with the returned documents and sent off to the model.
[screen-capture (4).webm](https://github.com/user-attachments/assets/792b4e13-c5d0-4208-9da5-76798e550c3c)
For more information on following Developer Certificate of Origin …

Add support for query request parsing in ml search resp processor

---

common/interfaces.ts
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/index.ts
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_prompt_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/index.ts
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/output_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/override_query_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/model_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/model_outputs.tsx

Refactors the components of the model input / output transforms into standalone components. This is the first step in #491.
Subsequent PRs may be going to a feature branch.
Makes progress on #491 

Refactor model input/output transform configurations

---

public/pages/workflows/workflows.tsx

- Adding experimental badge in header in Workflows list page
New home page with MDS enabled.
New home page with no MDS.
Old home page with MDS enabled. (No changes here)
Old home page with no MDS. (No changes here)
- Related to https://github.com/opensearch-project/dashboards-flow-framework/issues/461

Adding experimental badge in header in Workflows list page

---

.github/CODEOWNERS
MAINTAINERS.md

Add kamahuan as maintainer

---

common/constants.ts
common/interfaces.ts
public/configs/ml_processor.ts
public/pages/workflow_detail/workflow_inputs/input_fields/index.ts
public/pages/workflow_detail/workflow_inputs/input_fields/map_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/select_with_custom_options.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_expression_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_template_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/index.ts
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/model_inputs.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/utils/config_to_form_utils.ts
public/utils/config_to_schema_utils.ts
public/utils/config_to_template_utils.ts
public/utils/utils.ts

Continuation of #493. Opening to a feature branch so main stays stable. This PR breaks the advanced transform modals entirely.
This PR completes the new UX flows for configuring input transforms. At a high level, this adds support for:
- toggling between different transform types (static value vs. field vs. JSONPath transform vs. template)
- configuring JSONPath expressions / transforms via new modal
- configuring templates (and any sub-transform mappings) via new modal
Implementation details:
- updates the schema for the input map - this means changes in the UI config, Formik form, and yup schema to be compatible. Basically, we introduce a new field for each input map entry, called `transformType`, which allows dynamic rendering of different form components based on the type selected. …

Support different input transform types

---

common/constants.ts
common/interfaces.ts
public/configs/ml_processor.ts
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_expression_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_multi_expression_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_template_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/index.ts
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/output_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/model_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/model_outputs.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/edit_query_modal.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/utils/config_to_form_utils.ts
public/utils/config_to_schema_utils.ts
public/utils/config_to_template_utils.ts
public/utils/utils.ts

Continuation of #495. This PR adds configurable transforms based on transform type. Similar to input transforms, there is a set of available transform types that can be configured in the form. They dynamically render different inputs based on the type selected:
1. `Field`: a field rename to a new document field. Displays freeform text input. Will add a single entry in `output_map` processor config.
2. `Expression`: define a set of transforms to new document fields. Displays a button to configure in a new modal. Since the model output can be complex & nested, this lets users flexibly pull out multiple values from a single model output field. Will add at least one single entry in `output_map` processor config.
3. `No transformation`: keep the field as-is and persist as a new document field. …

Support different output transform types

---

common/constants.ts
common/interfaces.ts
public/general_components/index.ts
public/general_components/query_params_list.tsx
public/pages/workflow_detail/components/export_modal.tsx
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/tools/ingest/ingest.tsx
public/pages/workflow_detail/tools/query/query.tsx
public/pages/workflow_detail/tools/tools.tsx
public/pages/workflow_detail/workflow_detail.test.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_expression_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_multi_expression_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_template_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/override_query_modal.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/edit_query_modal.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/new_workflow/index.ts
public/pages/workflows/new_workflow/utils.ts
public/utils/utils.ts

This PR greatly improves the search experience and flexibility in few different ways:
1. Updates the `EditQueryModal` to dynamically display parameters/placeholders in a query that matches the pattern `{{<placeholder>}}`. Users can fill these out (either text or binary - binary accepts an image input and performs the conversion to binary automatically), and execute search directly within the modal, to quickly verify different queries with different parameters, before saving.
2. Updates the `Search` tab in the Inspector to have similar functionality as ^; a default query will be provided, but users can override in this sandboxed env. They can search and view results all within this panel. Additionally, they can search with/without any configured search pipeline (no search pipeline allowed …

Add parameterized search

---

common/constants.ts
common/interfaces.ts
documentation/tutorial.md
public/pages/workflow_detail/tools/query/query.tsx
public/pages/workflow_detail/tools/tools.tsx
public/pages/workflows/new_workflow/utils.ts
public/utils/config_to_template_utils.ts
public/utils/utils.ts

PR to update variety of things:
1. Adds a `schema_version` within the `ui_metadata` field to track schema changes over time. This follows the pattern used in [AD](https://github.com/opensearch-project/anomaly-detection/blob/main/src/main/resources/mappings/config.json#L3C4-L5C7) for maintaining schema versions of the detector JSON object mappings within the system indices. Over time, if there are substantial UI changes requiring new logic to parse to/from the `ui_metadata` schema (e.g., some new UI-only construct/idea), we can add such logic, bump the schema version, and add branching logic to parse the legacy schema to the new schema. Future work can be done to optimize/minimize the amount of data and help de-risk BWC concerns and the chances of requiring schema version bumps. For more …

Add `ui_metadata` versioning; other small fixes

---

public/pages/workflow_detail/components/export_modal.tsx
public/pages/workflow_detail/components/header.tsx
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/tools/query/query.tsx
public/pages/workflow_detail/workflow_detail.test.tsx
public/pages/workflow_detail/workflow_inputs/config_field_list.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/boolean_field.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/search_inputs.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/workflow_list/delete_workflow_modal.tsx
public/pages/workflows/workflow_list/workflow_list.tsx
public/utils/config_to_template_utils.ts

This PR updates the navigation across ingest and search. The main changes include:
- automatic bottom bars that pop up if there are changes detected that will impact the resources created (or if creating for the first time). Within them, can either update the resources, or undo changes and revert to the last saved state. These also work to block the complexity around buttons being enabled/disabled which the users don't need to care about, as navigation is disabled by default while the bottom bar is present and changes need to be updated or reverted first.
- state updates of the resources indicating if they are provisioned or not. Shows ingest state on ingest flow, and ingest/search states on search flow for easier visibility
- simplifies search flow: rather than handling search within the …

Simplify form navigation

---

opensearch_dashboards.json
server/index.ts
server/types.ts

- This PR is related to adding feature flag for Flow framework Dashboards.
- This gives ability to enable or disable OpenSearch flow plugin in Dashboards.
[screen-capture (30).webm](https://github.com/user-attachments/assets/22ecaf8e-0ee3-455a-ac4e-5ff5a217b678)
Tested:
- Verified by Enabling, disabling feature flag in config/opensearch_dashboards.yml .
- When flowFrameworkDashboards.enabled:false, OpenSearch Flow Will not be visible.
- By default it is true.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origi …

Adding feature flag to OpenSearch Flow

---

common/interfaces.ts
public/general_components/index.ts
public/general_components/results/index.ts
public/general_components/results/results.tsx
public/general_components/results/results_json.tsx
public/general_components/results/results_table.tsx
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/tools/query/query.tsx
public/pages/workflow_detail/tools/tools.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/edit_query_modal.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflow_detail/workspace/workspace.tsx

This PR primarily improves the search response rendering. Instead of a single JSON editor view showing the list of _sources from the response, now offer 2 modes: 1/ a more structured view of the sources in a tabular format with pagination to look through the data, or 2/ a raw JSON view which shows the full response. This ensures that any data users are interested outside of the _source hits (e.g., aggregations, ext field values, etc.) is still accessible.
Implementation details:
- adds new `Results` component and sub-components containing the new rendering options
- makes new `Results` component accessible in the edit query modal and the query tab of the Inspector, which is the 2 places search is supported
- adds new "Search" button to open/close the search-related components in the edit …

Improve search response rendering; other minor fixes

---

common/constants.ts
common/interfaces.ts
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_template_modal.tsx
public/pages/workflows/new_workflow/quick_configure_inputs.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/pages/workflows/workflow_list/workflow_list.test.tsx
public/pages/workflows/workflow_list/workflow_list.tsx

Mixed-bag PR, includes the following:
- changes the variable insertion in the template from a copy/paste flow, to a single "insert" flow. Cursor position is persisted in the prompt code editor, and when users click "insert" on a particular template var, the formatted var is injected at such position. Further improvements to help automate these things, as well as better & more prompt templates, will come in the future when those flows are finalized and UX feedback is gathered.
- improves the RAG quick-configure presets to follow the new pattern of a model expecting a single 'prompt' field. This is defined in quick create, and used alongside any contextual field (so far, the "text field") and automatically attach as a template variable.'
- improves default transform types for the input / …

Support inserting template vars at cursor position; improve RAG preset

---

public/general_components/processors_title.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/enrich_data.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_expression_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_multi_expression_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_template_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/model_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/model_outputs.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/enrich_search_request.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/enrich_search_response.tsx

This PR implements Option 1 stated in the issue #528. All advanced transform modals now show the query param list (if applicable) under search-related contexts, such that the query, or the response from the query, can be fully populated with a valid query before executing and fetching the preview source data.
Other minor improvements:
- prevent duplicate keys when configuring inputs/outputs of ML processors. Technically can be done, but likely not user-intended. Users can still add any mappings they like, but it will be freeform text if there is no remaining preset options based on the model interface.
- spacing issues on a few of the modals
- removed optional flag for search processors. misleading in the case of users creating a search pipeline, and then trying to revert, as fine-grained …

Add query param list in advanced transform modals

---

common/constants.ts
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_template_modal.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx

This PR improves the prompt building experience by:
1. Improving the presets. Added several based on some suggested ones here: https://docs.aws.amazon.com/bedrock/latest/userguide/prompt-templates-and-examples.html
2. Automatically generating the unique list of nested vars based on the prompt presets, if any placeholders are found. This helps the mental model and association of how the parameters/placeholders in the prompts are tied to the form entries.
Demo video, showing the updated RAG preset, and then going through the added presets and associated generated nested parameter vars.
[screen-capture (8).webm](https://github.com/user-attachments/assets/5dcf6dbc-6e01-4222-84bf-68a0bff3fd99)
N/A
By submitting this pull request, I confirm that my contribution is made under the terms of the …

Improve prompt presets and prompt var generation

---

common/constants.ts
public/general_components/index.ts
public/general_components/jsonpath_examples_table.tsx
public/pages/workflow_detail/tools/query/query.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/override_query_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/model_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/model_outputs.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/edit_query_modal.tsx
public/utils/config_to_schema_utils.ts

Small PR with few improvements:
- always show the query in the search tab. if updated from the default configured query (if in search context), show a button to revert back
- add loading state to the search button to prevent overloading, and for visibility if searches take a long time (e.g., RAG flows)
- makes 'OverrideQueryModal' consistent with other modals by persisting temporary form s.t. query is only updated if users explicitly save
- adds check for `JSONArray` form types to validate on byte size; this prevents hitting OSD REST request limits when executing APIs, such as ingest. For example, adding byte64 encodings in ingest may not exceed the already-defined doc count of 1000, but may exceed the byte count, and thus fail at runtime. This prevents even setting the docs field to …

Misc improvements

---

common/constants.ts
public/general_components/jsonpath_examples_table.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_expression_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_multi_expression_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_template_modal.tsx
public/utils/config_to_schema_utils.ts

This PR updates and leverages the JSONPath examples table in 3 different modals, where JSONPath can be written. Adds a "learn more" button to open/close the popover with all of the details, as well as a link to the JSONPath documentation used.
Demo video, showing it in the 3 modals:
[screen-capture (13).webm](https://github.com/user-attachments/assets/ed39acf1-1765-4355-be3c-b2778195ee29)
Other: simplifies and makes model input/output tooltips consistent.
Other: simplifies error messaging for JSONArray inputs that are too large
N/A …

Add JSONPath examples / details in relevant modals

---

public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_multi_expression_modal.tsx

There was some leftover code overriding the `full_response_path` to the full_response_path as persisted in the modal-level form, which has been removed. This removes that override to use the current Formik `values` value of `full_response_path`.
Tested by fetching preview with full_response_path set to false -> true -> back to false and re-running preview, works as expected.
N/A

Fix bug of unsaved `full_response_path` not updating when fetching output preview data

---

common/constants.ts
public/pages/workflow_detail/workflow_inputs/ingest_inputs/advanced_settings.tsx
public/pages/workflows/new_workflow/quick_configure_inputs.tsx
public/utils/utils.ts

This PR adds default index mappings and index settings as ML processors are added / removed from ingest pipelines in real-time. The main idea is to add/remove any `knn_vector` field mappings, and update `index.knn` to `true`/`false` as users add or remove ML-related ingest processors, that contain any known embedding models. These 2 settings are critical and required for proper knn search to happen. Currently, the backend does not show any errors if these aren't configured correctly, and leads to user confusion when later seeing that there are no embeddings added. By adding this, this helps minimize users missing these configurations if knn search is desired.
Testing:
- tested all different output map transformation types on the UI, and how adding / removing one/multiple ML processors, …

Add auto-generation of index mappings & settings based on processors

---

public/general_components/index.ts
public/general_components/processing_badge.tsx
public/global-styles.scss
public/pages/workflow_detail/components/edit_workflow_metadata_modal.tsx
public/pages/workflow_detail/components/export_modal.tsx
public/pages/workflow_detail/components/header.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data_modal.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/boolean_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_expression_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_multi_expression_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_template_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/override_query_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/model_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/model_outputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/normalization_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/text_chunking_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/edit_query_modal.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/new_workflow/quick_configure_inputs.tsx
public/pages/workflows/new_workflow/use_case.tsx
public/pages/workflows/workflows.tsx

Continuation of #549, #554.
Variety of small UX updates / fixes:
- adds a gear button & corresponding modal to update workflow metadata, including the workflow name and description
- updates layout of one-to-one button to a top-level switch on the "inputs" section for ML search response processors
- fixes button state issues on ingest and search when importing a workflow with previously-provisioned resources
- fixes the many-to-one / one-to-one labels for all processor contexts
- removes or updates help text in few places
- layout and minor UX updates to ML processor inputs/outputs
- layout updates to Workflow List and New Workflow pages
- layout updates to modals, move styling to central scss file
- layout updates to New Workflow use case cards
- add default expression entry in …

UX fit-n-finish updates III

---

common/constants.ts
public/configs/ingest_processors/copy_ingest_processor.ts
public/configs/ingest_processors/index.ts
public/pages/workflow_detail/workflow_inputs/processors_list.tsx
public/utils/config_to_workspace_utils.ts

Onboards the `copy` ingest processor: https://opensearch.org/docs/latest/ingest-pipelines/processors/copy/
Tested that it shows up in the ingest processor dropdown, and functionally works as expected. All exposed configurations come from the documentation.

Onboard copy ingest processor

---

common/constants.ts
common/interfaces.ts
common/utils.ts
public/pages/workflow_detail/components/export_modal.tsx
public/pages/workflow_detail/workflow_detail.test.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/json_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/override_query_modal.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/search_inputs.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/new_workflow/quick_configure_inputs.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/pages/workflows/new_workflow/utils.ts
public/store/reducers/opensearch_reducer.ts
public/utils/utils.ts
server/resources/templates/custom.json
server/resources/templates/hybrid_search.json
server/resources/templates/multimodal_search.json
server/resources/templates/rag.json
server/resources/templates/semantic_search.json
server/resources/templates/vector_search_with_rag.json
server/routes/helpers.ts
test/utils.ts

Continuation of #559 . Several bug fixes and enhancements.
- adds a new "Vector search + RAG" preset, which allows selecting an LLM and an embedding model from the quick config menu. see demo video below
- removes auto-selected models in quick configure to prevent invalid models (e.g., LLM selected for some embedding model)
- change default fetch_all query's `size` to smaller value
- add fallback if invalid datasourceid / data source not found to prevent 500s from server-side
- propagate errors during bulk ingest as if it was a server-side error. This helps it be consistent and much more visible when troubleshooting errors in ingest pipelines, for example.
- update the form values in JSON fields `onChange`, not just `onBlur`. This prevents issues of button states not being updated until …

UX fit-n-finish updates IV

---

common/constants.ts
public/pages/workflow_detail/components/edit_workflow_metadata_modal.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data_modal.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/select_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/select_with_custom_options.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/text_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_template_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/override_query_modal.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/new_workflow/new_workflow.test.tsx
public/pages/workflows/new_workflow/quick_configure_inputs.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/pages/workflows/new_workflow/utils.ts
public/pages/workflows/workflows.tsx
server/resources/templates/rag.json

Continuation of #565, various UX bug fixes and minor improvements.
- surface sub-field-level form validation to help users uncover missing/invalid fields, particularly when configuring the ML transforms
- move model selection to top-level of quick config modal
- set default name to empty to prevent easily creating duplicate workflow names
- prevent duplicate workflow name (both in quick-config modal and in update workflow metadata modal)
- move the location and rename the override query modal
- fix bugs of model outputs not visible in the override query modal depending on certain transform types
- several component updates and wording changes to import data component + import data modal
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache …

UX fit-n-finish updates V

---

common/constants.ts
public/pages/workflow_detail/workflow_inputs/ingest_inputs/advanced_settings.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/ingest_data.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/override_query_modal.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/edit_query_modal.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/new_workflow/quick_configure_inputs.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/utils/utils.ts

Continuation of #567, various UX improvements and bug fixes:
- add guardrails on selecting an embedding model with unknown dimensions details, including a callout, and automatically opening the accordion from the quick configure menu
- gracefully handle partial provisioning failures. deprovision and show toast
- disambiguate parameters vs. placeholders in the query presets. The main idea is, the only dynamic values in the query that the users want to test with, should be separated from the placeholders that should be set to static fields, like a model id or text field, for example. Additionally, this prevents saving / updating the preset query, until such values are populated.
- add callout if an invalid dimension value is set.
Relevant screenshots:
By submitting this pull request, I …

UX fit-n-finish updates VI

---

README.md
common/constants.ts
public/pages/workflow_detail/components/edit_workflow_metadata_modal.tsx
public/pages/workflow_detail/workflow_detail.test.tsx
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/ingest_data.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data_modal.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/import_workflow/import_workflow_modal.tsx
public/pages/workflows/new_workflow/new_workflow.tsx
public/pages/workflows/workflows.tsx
public/utils/config_to_schema_utils.ts

Continuation of #570, contains various improvements and bug fixes
- adds confirmation modal when ingestion flow successfully updates and data is ingested
- updates default match_all size params for queries used to fetch backend resources
- improved index name validation: ensure it is of valid pattern, and prevent duplicate index names. Especially helpful when importing a provisioned workflow within the same cluster/datasource.

UX fit-n-finish updates VII

---

public/pages/workflow_detail/tools/query/query.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx

Update and add a few test IDs to work with the updated integration tests. Corresponding test changes tracked in https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1678
Closes #519 

Tune test IDs for integ tests

---

common/constants.ts
public/pages/workflow_detail/components/edit_workflow_metadata_modal.tsx
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/tools/tools.tsx
public/pages/workflow_detail/workflow_detail.test.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data_modal.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/get_started_accordion.tsx
public/pages/workflows/new_workflow/quick_configure_inputs.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/pages/workflows/workflow_list/columns.tsx
public/pages/workflows/workflow_list/workflow_list.tsx
public/pages/workflows/workflows.tsx

Continuation of #582, contains various UX fit-n-finish updates.
- reorders input transform type in dropdown
- reorders tabs in the inspector
- adds a "Get started" accordion on home page with general details and links to documentation
- updates form widths in edit metadata modal to be consistent with quick configure modal
- adds a 'description' column in the workflow list, updates columns widths accordingly
- misc small wording updates
Screenshots:

UX fit-n-finish updates X

---

common/constants.ts
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/utils/utils.ts
server/cluster/flow_framework_plugin.ts
server/routes/flow_framework_routes_service.ts

Updates few of the provisioning-related API calls to leverage new params offered to enforce synchronous provisioning with a configurable timeout - see PR: https://github.com/opensearch-project/flow-framework/pull/990
Setting timeout to 10s for now, as we have not run into problems with the existing manual check done after 1s prior.
This improves the plugin in a few ways:
- UX state updates as soon as provisioning/reprovisioning is completed
- UX state has much lower chance of getting out of sync; before, the plugin manually waited a set time and re-fetched the workflow details. Now, it will only fail if provisioning takes > the configured timeout of 10s.
Testing
- ensured existing flows work as expected, including exercising all changed API paths
Makes progress on #571 
By submitting this …

Integrate with synchronous provisioning feature

---

public/pages/workflow_detail/components/edit_workflow_metadata_modal.tsx
public/pages/workflow_detail/tools/resources/resource_list_with_flyout.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/advanced_settings.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data_modal.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflows/import_workflow/import_workflow_modal.tsx
public/pages/workflows/new_workflow/quick_configure_inputs.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/pages/workflows/workflow_list/resource_list.tsx
public/utils/config_to_schema_utils.ts

There are certain edge cases where the values called in `Object.values()` may be undefined or null, which crashes the webpage. This adds checks on all instances of `Object.values()` with a default value if the value is undefined/null.
There is an edge case of no workflows created (no system index) that leads to server-side error, which is incorrectly setting the redux store value of `workflows` to undefined, and causing a crash when trying to create a workflow, where `QuickConfigureModal` does a validation check on the workflow names, which is where an NPE can occur. This fixes that by auditing all instances of `Object.values()`.
For more information on following Developer …

Add NPE checks on Object.values() calls

---

public/configs/ingest_processors/text_embedding_ingest_processor.ts
public/configs/ingest_processors/text_image_embedding_ingest_processor.ts
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workflow_inputs/config_field_list.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/map_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/model_field.tsx
public/pages/workflow_detail/workflow_inputs/processors_list.tsx
public/pages/workflows/new_workflow/new_workflow.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/utils/config_to_template_utils.ts
public/utils/utils.ts

This PR allows the legacy presets (and associated legacy processors) to work as expected end-to-end. More details:
- exposes all required fields in the processor form
- updates the raw `model_id` field to be a `model` for consistency and user friendliness
- ensures the processors have special logic in the template conversion utils to form a proper/valid definition
- integrates with the quick-configure modal, such that the input fields are propagated to auto-fill everything, including the processor form values, and the query. See demo video below.
Other minor fixes:
- adds NPE check on undefined connector
- clears processor error state if navigating off of details page
Demo video, showing the presets with the pre-populated values for the legacy processors. …

Integrate legacy presets with quick-configure fields

---

public/pages/workflow_detail/tools/query/query.tsx
public/pages/workflow_detail/workflow_inputs/processors_list.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/search_inputs.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/new_workflow/new_workflow.tsx
public/route_service.ts
public/store/reducers/opensearch_reducer.ts
public/store/reducers/workflows_reducer.ts
public/utils/config_to_template_utils.ts
public/utils/utils.ts
server/cluster/flow_framework_plugin.ts
server/routes/flow_framework_routes_service.ts
server/routes/opensearch_routes_service.ts

#591 and #598 added integrations with backend API enhancements only available in 2.19+. Since we want to support 2.17 backend datasources as well, we need to have conditional logic for executing these updated APIs. This PR adds that logic by:
1. Only running synchronous provisioning if the data source version is >=2.19
2. Only running the search with `verbose_pipeline=true` if the data source version is >=2.19.
It does this by propagating the data source version where applicable, and executing different APIs based on the semver checks.
Also adds an NPE check on the model fields in the legacy processors during template conversion.
Testing:
- tested without any datasource, with datasource 2.19+, and with datasource <2.19 for both APIs
- audited all places where API is triggered from …

Support 2.17 BWC with latest backend integrations

---

common/interfaces.ts
public/general_components/results/ml_outputs.tsx
public/general_components/results/results.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/utils/config_to_template_utils.ts

This improves the RAG preset experience in a few ways:
1. Changes the default behavior of ML response processors (when configured for many-to-one), to store the outputs under `ext.ml_inference` by default. This way, a single ML response is returned in the overall response by default for these scenarios. Existing functionality for ML response processors in other contexts, and/or when one-to-one is configured, remains unchanged.
2. Auto-navigate to the 'ML outputs' tab if there is values found
3. Re-ordering and minor renaming of the tabs under 'Results'
4. Minor reformatting the 'ML outputs' tab content
Demo video, showing the end-to-end RAG preset experience and propagation of the LLM response:
[screen-capture (24).webm](https://github.com/user-attachments/assets/b05de284-b380-4655-af73-85 …

Improve RAG preset experience

---

common/constants.ts
public/pages/workflow_detail/tools/errors/errors.tsx
public/pages/workflow_detail/tools/tools.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/model_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/edit_query_modal.tsx
public/pages/workflows/new_workflow/new_workflow.tsx
public/pages/workflows/workflow_list/workflow_list.test.tsx
public/pages/workflows/workflow_list/workflow_list.tsx
public/pages/workflows/workflows.test.tsx
public/pages/workflows/workflows.tsx
public/utils/utils.tsx

Continuation of #613. Contains various enhancements & bug fixes.
- Fixes bug of `Get started` accordion not visible when the global `useNewHomePage=true`.
- Only show relevant workflow types for BWC 2.17 datasources
- Reformat processor errors, support rendering arbitrary components in Errors tab for specialized error rendering
- Remove redundant description text in workflow list
- Add back custom/empty workflow template for BWC 2.17 datasources
- Move import data button (empty state)
- Move search button in query editor modal
- Add refresh button in ModelField to fetch updated models
- Add refresh button in "no models found" callout in ML processor form component
For more …

UX fit-n-finish updates XII

---

public/pages/workflow_detail/workflow_inputs/processors_list.tsx
public/pages/workflows/new_workflow/new_workflow.test.tsx
public/pages/workflows/new_workflow/new_workflow.tsx
public/route_service.ts
public/store/reducers/opensearch_reducer.ts
public/store/reducers/presets_reducer.ts
public/utils/utils.tsx

Currently in the new work flow page, when user click local data source, it shows a loading state and does not render any presets. This PR fix this issue by getting version from the datasource and render the presets based on the data source version.
None

fix error that local cluster cannot get version

---

common/constants.ts
public/pages/workflow_detail/workflow_inputs/input_fields/model_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/ml_processor_inputs.tsx

Updates the model options to include `EuiHealth` component, setting as warning color if missing model interface. Tunes the missing interface callout text and adds a link to the update model API.

Update model options and callout

---

public/pages/workflow_detail/workflow_inputs/search_inputs/search_inputs.tsx
public/pages/workflows/workflow_list/workflow_list.tsx

Fixed the following issues.
- when switching between datasources loading state should be displayed instead of delay.
-  “Transform query” section still shows up for a moment before being hidden when navigated to search flow. 
[screen-capture (43).webm](https://github.com/user-attachments/assets/3e911459-0459-4d5d-971e-3a5484afd932)

Bug fixes XIII

---

common/constants.ts
public/utils/config_to_template_utils.test.tsx
public/utils/config_to_template_utils.ts

#574 defines common short-form versions of queries that can lead to runtime failures if ML search request processors are defined/dependent on them. This PR implicitly updates any paths defined on the short-form, and makes them compatible with the long-form, for all relevant term-level and full-text queries, + aggregations.
There are some remaining edge cases that can be done in follow-up PRs, they are listed in https://github.com/opensearch-project/dashboards-flow-framework/issues/574#issuecomment-2669563040
Also added several more preset queries for convenience. By default, they are in long/extended form where applicable.
Added UT.
Also manually ensured for each added query (and aggregation query) that it:
1. Compiles in default (long/extended-form where applicable)
2. Compiles in …

Implicitly update input maps defined on non-expanded queries (common cases)

---

public/pages/workflow_detail/workspace/workspace.tsx

Before, the 'JSON' tab in the workspace would be empty, if nothing was provisioned. This is because it was fetching from the concrete workflow details. Changed to update in real-time on the _proposed_ provision template as users make form updates. This also means it will be populated even when nothing has been provisioned yet.

Show interim JSON provision flow even if provisioned

---

common/constants.ts
documentation/models.md
public/pages/workflow_detail/workflow_inputs/input_fields/model_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/models_info_popover.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx

- Added popover to display links to suggested models 
- Included both Embedding and Large Language model examples. 
- Added Semantic Search Template Query Preset. 
- Added documentation for DeepSeek, OpenAI GPT 3.5, Cohere Embed Models. 
Semantic Search Template Query Preset:
Semantic Search Neural Query Preset:

added popover to display links to suggested models

---

common/interfaces.ts
public/app.tsx
public/configs/ingest_processors/copy_ingest_processor.ts
public/configs/ingest_processors/text_chunking_ingest_processor.ts
public/configs/ingest_processors/text_embedding_ingest_processor.ts
public/configs/ingest_processors/text_image_embedding_ingest_processor.ts
public/configs/ml_processor.ts
public/configs/search_response_processors/collapse_processor.ts
public/configs/search_response_processors/normalization_processor.ts
public/configs/search_response_processors/rerank_processor.ts
public/configs/sort_processor.ts
public/configs/split_processor.ts
public/pages/workflow_detail/components/header.tsx
public/pages/workflow_detail/workflow_detail.test.tsx
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workflow_inputs/config_field_list.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/normalization_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/new_workflow/utils.ts
public/utils/config_to_form_utils.ts
public/utils/config_to_schema_utils.ts

PR with various improvements:
- changes `description` field types to textarea, instead of single text field that prevents whitespace by default. All processors that currently expose this field have been updated.
- catches 5 more scenarios of navigating away from the details page, if unsaved changes are detected. This includes the native browser back/forward buttons, the breadcrumbs links, exit buttons, home buttons, and side nav buttons. Adds a browser-native confirmation modal to confirm or deny the navigation. See screenshot below. See #469 for more details on the scenarios.
- auto-populates more of the default optional fields for the normalization processor, as well as bubbling up the 'weights' field to make it more accessible. See screenshots below
- prevent navigating to search if …

Various bug fixes & improvements

---

public/pages/workflow_detail/tools/query/query.tsx
public/pages/workflow_detail/tools/resources/resource_flyout.tsx
public/pages/workflow_detail/tools/resources/resource_flyout_content.tsx
public/pages/workflow_detail/tools/resources/resource_list_with_flyout.tsx
public/pages/workflow_detail/tools/resources/resources_flyout.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/workflows.tsx
public/utils/config_to_template_utils.test.tsx
public/utils/config_to_template_utils.ts
public/utils/utils.tsx

This PR adds several new buttons in the form headers for performing different actions:
- "Test flow" button which automatically opens and navigates to the "Test flow" tab in the inspector
- "Details" button which automatically opens a flyout for the relevant resources (if created) for a particular context. On ingest, at most show the index and ingest pipeline (nest them under tabs if both found). On ingest, at most show the search pipeline
- Update the newly-added flyouts and existing flyouts to show usage examples leveraging runtime data if found - for example, use the configured index name, ingest pipeline name, search pipeline name, and/or search query, if found.
Also:
- moves data source version checks into a reusable custom hook
- fixes query parsing bug which caused failures on …

Add functional buttons in form headers; fix query parse bug

---

public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_expression_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_multi_expression_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_template_modal.tsx
public/pages/workflow_detail/workflow_inputs/processors_list.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/search_inputs.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/import_workflow/import_workflow_modal.tsx
public/pages/workflows/new_workflow/new_workflow.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/utils/utils.tsx

If there is a datasource ID, but no known version found, we cannot guarantee that the simulate API will be available. This PR adds a reusable custom hook to check for that scenario, and adds conditional checks for all places where `simulatePipeline()` is called:
- `WorkflowInputs` component
- Configure expression modal
- Configure multi-expression modal
- Configure template (prompt) modal
To make this work, `getEffectiveVersion()` was updated slightly to return `undefined` instead of defaulting to the minimum version, since this undefined/empty case now needs to be handled. Audited all places where `getEffectiveVersion` is called, where a minimum version is wanted, and updated there. Updated the name to `getDataSourceVersion()` to reflect this more clearly as well.
Also moves …

Block simulate API calls if datasource version is missing

---

common/constants.ts
public/general_components/service_card/plugin_card.tsx
public/pages/workflows/import_workflow/import_workflow_modal.tsx
public/pages/workflows/workflows.tsx

Updates all instances (besides the URL and certain description texts) from "OpenSearch Flow" -> "AI Search Flows". This includes the side navigation item, the breadcrumbs, the plugin title on the home page, and other various texts.
Note the underlying plugin ID remains unchanged to prevent build/registration issues with core OSD. Only user-facing changes have been changed.
- all UT passes
- all IT passes
```
Spec                                              Tests  Passing  Failing  Pending  Skipped  
┌────────────────────────────────────────────────────────────────────────────────────────────────┐
│ ✔  plugins/dashboards-flow-framework/c      02:43        6        6        -        -        - │
│    reate_workflow_spec.js …
```

Update visible plugin name to 'AI Search Flows'

---

package.json
public/general_components/service_card/plugin_card.tsx

- Update plugin card in Search Overview Page and rearrange "Try AI Search Flows card". 
- **Please recheck when backporting. `Removed "plugin_version": "2.19.0.0" in package.json`. Fixed yarn build script accordingly.** If needed will raise separate PR for main. 
- Relavant PR in OSD https://github.com/opensearch-project/OpenSearch-Dashboards/pull/9500

Update plugin name and rearrange Try AI Search Flows card

---

package.json
public/general_components/service_card/plugin_card.tsx

- Fixed yarn build script to use right plugin version and rearranged "Try OpenSearch Flow" card in Search Overview Page
- Backporting to main #664 
[List any issues this PR will resolve]

Fixed yarn build script to use right plugin version and rearranged "Try OpenSearch Flow" card in Search Overview Page (Backport Main)

---

public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_expression_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_multi_expression_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/modals/configure_template_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/model_inputs.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/utils/utils.tsx

Fixes a few missed edge cases where the doc parsing failed after the switch to JSONLines format. Also moves common logic into a helper fn.
Demo video showing the autofilling with different inputs:
[screen-capture (28).webm](https://github.com/user-attachments/assets/0db0b620-fe65-4269-8021-f49b36e47a4f)

Fix missed UI autofilling after JSON Lines change

---

public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data_modal.tsx
public/utils/utils.tsx

This PR updates the new index mappings to match that of the existing index, if "select from an existing index" option is selected when fetching the source data. Persists any pre-configured vector field mappings, if found. For example, suppose there is a `my_vector` field of type `knn_vector`. If source data is selected and the overall index mappings are updated, `my_vector` is still persisted. See demo video below.
Also cleans up some unnecessary logic of updating the input map based on the source data selection, which could cause bugs under certain edge cases.
Demo video:
[screen-capture (26).webm](https://github.com/user-attachments/assets/3b36f3b1-41a8-48ea-8068-4bf10c144094)
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

Update new index mappings if selecting from existing index

---

public/pages/workflow_detail/tools/query/query.tsx
public/pages/workflow_detail/tools/tools.tsx

Currently, a lot of the search-related state is localized to the tab component, and as a consequence gets reset across tab switches and re-renderings. This PR moves the following state params to the parent `Tools` component to prevent lost data:
- query request
- query params
- query response
Also, adds a query preset dropdown consistent with the other locations it is available (in the edit query modal and override query modals).
Demo video showing the persisted state:
[screen-capture (27).webm](https://github.com/user-attachments/assets/4da836d8-9e37-47fb-b4c3-0509a5d8fc00)
Screenshot showing the query preset in the panel:
N/A
For more information on following Developer …

Persist state across Inspector tab switches; add presets dropdown

---

common/interfaces.ts
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/model_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/model_outputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/utils.ts

Adds caches for the input/output forms for ML processors, such that values are cached across different transform types. The idea is users can easily toggle between types and not lose lost configuration. Note this is only cached while the component is loaded on the page; a navigation away or page refresh will lose the cached state.
Implementation-wise, this adds a util fn shared across `model_inputs` and `model_outputs` to update a cache, and pre-populate values _from_ the cache, as users change underlying transform types within the input/output maps.
Demo video:
[screen-capture (30).webm](https://github.com/user-attachments/assets/da11767b-e943-4441-b20d-6b29c2553db8)
For …

Cache form across ML transform types

---

public/component_types/other/search_request.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/utils/utils.tsx

In the search flow, if the query is Knn query and the source index file is not knn, should pop up a callout box.
[682](https://github.com/opensearch-project/dashboards-flow-framework/issues/682)

add callout if knn query does not have knn index

---

public/pages/workflow_detail/workflow_inputs/processors_list.tsx

Add icons so that users can use the icons to move the processors up and down for one step once a time.
https://github.com/user-attachments/assets/400071d2-67a1-4808-bbe7-87cc0c3d364a

adding icons to reorder processors up and down

---

public/pages/workflow_detail/workflow_inputs/input_fields/text_field.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx

When the user creates a new workflow, a quick config modal will pop up. This PR make the first field of the modal focused.
NA

add focus to the first field for the quick config modal

---

common/interfaces.ts
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/model_inputs.tsx
public/utils/config_to_schema_utils.ts
public/utils/config_to_template_utils.ts
public/utils/utils.tsx

Recent changes have added more guardrails, such that users cannot add/remove input mappings if a model interface is defined. However, if a field is optional, users may not want to include. This relaxes the constraints such that if an optional field is found, it is displayed on the UI, and there are no validations on the value if left empty.
Implementation details: adds an `optional` field in the model input form interface, defaulting to `false` for smooth BWC experience. Updates `config_to_schema_utils` to relax the constraints if the form field is optional. Updates `config_to_template_utils` to filter out empty optional fields and omit altogether when building the ML processor config. Also adds a helper util fn `parseRequiredModelInputs()` to fetch and filter the required vs. optional …

Support optional model inputs

---

common/constants.ts
public/configs/search_response_processors/ml_search_response_processor.ts
public/pages/workflow_detail/workflow_inputs/input_fields/boolean_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/text_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/model_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/model_outputs.tsx
public/utils/config_to_template_utils.ts

Misc form-related enhancements to the ML processor inputs:
1. Loosens the constraints on the "Custom string" data transform value to allow for whitespace, which could be a common config value set. (for example, an LLM with 2 inputs, one being an image string, another being directions on what to do with the image - "Describe the image", "What is in the image?", etc.)
2. Allows flexibility and custom toggling of how the model response is stored in the search response context, when applicable. Before, the behavior was hardcoded to always store the responses nested within `ext.ml_inference`, which is the preferred way to view model outputs in the final search response. But, some use cases, such as batched reranking, we may want to write back to the documents themselves instead of storing in …

Support whitespace for string constant; support ext toggling on ML resp processors

---

.github/CODEOWNERS
MAINTAINERS.md

Revert #499 to follow standard procedure for nomination & determination of maintainer status for this repo.

Revert "Add kamahuan as maintainer"

---

CHANGELOG.md
common/constants.ts
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/tools/tools.tsx
public/pages/workflow_detail/workflow_detail.test.tsx
public/pages/workflow_detail/workspace/workspace.tsx
test/jest.config.js
test/mocks/html_id_generator.ts
test/mocks/uuid_mock.ts

Integrate preview panel as one of the tabs in the inspector panel, leaving more space for the right panel.
NONE

Integrate preview panel into inspector panel 

---

common/constants.ts
public/pages/workflow_detail/component_input/component_input.tsx
public/pages/workflow_detail/component_input/ingest_inputs/source_data.tsx
public/pages/workflow_detail/component_input/ingest_inputs/source_data_modal.tsx
public/pages/workflow_detail/component_input/input_fields/json_lines_field.tsx
public/pages/workflow_detail/component_input/input_fields/model_field.tsx
public/pages/workflow_detail/component_input/search_inputs/edit_query_modal.tsx
public/pages/workflow_detail/left_nav/left_nav.tsx
public/pages/workflow_detail/left_nav/nav_content/ingest_content.tsx
public/pages/workflow_detail/left_nav/nav_content/nav_components/processor_list.tsx
public/pages/workflow_detail/left_nav/nav_content/search_content.tsx
public/pages/workflow_detail/tools/query/query.tsx
public/pages/workflows/get_started_accordion.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/pages/workflows/workflows.tsx

More misc improvements
- tune missing interface callout and show in the quick-configure modal
- move 'Edit' button to top-level in component_input panel
- source data modal improvements: validate on keystroke, and improve spacing. Together, these improve the error handling and visibility if users manually enter JSONLines
- persist a search button after running successful search in Edit Query panel
- make certain transformations visible in search panel, even if disabled (no search pipeline)
- expand the 'Get started' accordion when the workflow list is empty
- fix bug of overflow showing when collapsing search accordion
- various minor spacing updates
- make expand/collapse btn be `display=base` to be more visible
Screenshots:
By submitting this pull request, I confirm that my contribution …

Misc improvements II

---

public/general_components/results/results.tsx
public/pages/workflow_detail/component_input/component_input.tsx
public/pages/workflow_detail/component_input/input_fields/model_field.tsx
public/pages/workflow_detail/left_nav/left_nav.tsx
public/pages/workflow_detail/left_nav/nav_content/ingest_content.tsx
public/pages/workflow_detail/left_nav/nav_content/nav_components/nav_component.tsx
public/pages/workflow_detail/left_nav/nav_content/nav_components/processor_list.tsx
public/pages/workflow_detail/left_nav/nav_content/search_content.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx

Continuation of #735.
- add default icons for processors - all being the same `compute` icon type
- fixes logic of "missing interface" callout to only render if datasource >= 2.19, and fixes an issue of it unnecessarily showing for certain model types in the quick configure modal
- updates the "Run query" and "Search results" panels to be static, unclickable text to prevent confusion on the content. Later on, when there is a standard pattern with contextual info for all component types, can add back.
- add/update some test IDs to be compatible with existing integ tests
- Add informational tooltips for leftnav actions
- Fixes bug of certain scenarios causing hits table not to refresh correctly
- Fix index creation failed on re-enabling ingest
- Make processor icon error color if applicable …

Misc improvements III

---

release-notes/opensearch-flow-framework-dashboards.release-notes-3.1.0.0.md

Add release notes for 3.1

---

public/route_service.ts
public/store/reducers/ml_reducer.ts
public/store/reducers/opensearch_reducer.ts
public/store/reducers/presets_reducer.ts
public/store/reducers/workflows_reducer.ts
public/utils/utils.tsx

Changes the error handling pattern for server-side errors. Rather than propagating strings and checking for errors based on `instanceof HttpFetchError`, we throw the errors directly, and catch them to be rejected in redux. This prevents issues under certain bundled builds, where the `instanceof` check will fail, and an error will be swallowed, leaving to corrupt redux store variables and unexpected NPEs.
Closes #788 

Improve error handling from server-side
