opensearch-project/dashboards-flow-framework

.github/workflows/draft-release-notes.yml
.github/workflows/lint.yml
DEVELOPER_GUIDE.md
README.md
common/constants.ts
opensearch_dashboards.json
package.json
public/app.tsx
public/index.ts
public/pages/overview/overview.tsx
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflows/workflows.tsx
public/plugin.ts
public/render_app.tsx
public/types.ts
public/utils/constants.ts
server/index.ts
server/plugin.ts
server/types.ts

Manual backport of #83 due to version differences causing merge conflicts.
[List any issues this PR will resolve]

[Backport 2.x] Update legacy naming (#83) (#84)

---

.github/CODEOWNERS
MAINTAINERS.md

Adds @saimedhi / @minalsha as codeowners to be able to review, approve, and merge PRs.

Add repo owners

---

opensearch_dashboards.json
package.json
server/resources/templates/hybrid_search.json
server/resources/templates/neural_sparse_search.json
server/resources/templates/semantic_search.json

Bump version to 2.16

---

public/app.tsx
public/plugin.ts
public/render_app.tsx

- This PR adds new navigation changes to Flow Framework Dashboards
- Testing Recording 1 -[b10ccf87-958a-4894-9f10-f505a4969701.webm](https://github.com/user-attachments/assets/31441f24-ee6c-44ed-bc00-edb917846f0a)
[screen-capture (6).webm](https://github.com/user-attachments/assets/e7dafa58-1c95-4aff-a716-268e81b897b4)
Related Issue: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/7029

Side Nav Redesign

---

public/pages/workflows/workflows.tsx

Fix description container in the new header

Fix description container in the new header

---

opensearch_dashboards.json
public/pages/workflow_detail/components/header.tsx
public/pages/workflows/workflows.tsx
public/utils/utils.ts

This PR filters out the versions which are not supported when MDS support is enabled
[screen-capture (17).webm](https://github.com/user-attachments/assets/9b122883-b28a-48f1-be08-76b2e5078df8)

MDS Version Decoupling

---

common/constants.ts
public/pages/workflow_detail/components/export_modal.tsx
public/pages/workflow_detail/components/header.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workspace/workspace.tsx

Small usability PR to add and improve some of the helper text in the Preview's `Workspace` panel, and add more helper text in `ExportModal`. Also, tunes some minor spacing alignment issues.
N/A

Add and improve some helper text; fix minor spacing

---

public/pages/workflow_detail/tools/tools.tsx
public/pages/workflow_detail/workflow_detail.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/map_array_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/number_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/select_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/text_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/output_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/edit_query_modal.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflows/import_workflow/import_workflow_modal.tsx
public/pages/workflows/workflow_list/workflow_list.tsx
public/pages/workflows/workflows.tsx

Use smaller and compressed variants of buttons and form components

Use smaller and compressed variants of buttons and form components

---

public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx

Without autosave, there is a certain edge case that occurs more often, causing a bug:
- user provisions ingest
- user navigates to search
- user provisions search + runs query
- user immediately re-runs query
- form fails, due to missing values in the form's `index.search` field
The issue arises because the search form value isn't populated until the user enters the search form page (if upon first entry). When re-running the search query, we automatically attempt to re-provision, even if no template changes. Thus, the request fails, and even any UI form updates (including `index.search` field) are not updated, due to it re-fetching the (now out-of-date) persisted workflow via a `get workflow` API call executed immediately after.
This PR fixes all of those edge cases by adding a check to …

Handle reprovision failure edge case

---

public/general_components/multi_select_filter.tsx
public/general_components/processors_title.tsx
public/general_components/service_card/search_studio_card.tsx
public/pages/workflow_detail/components/export_modal.tsx
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/tools/errors/errors.tsx
public/pages/workflow_detail/tools/resources/resources.tsx
public/pages/workflow_detail/tools/tools.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/ingest_data.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/configure_prompt_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/output_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/override_query_modal.tsx
public/pages/workflow_detail/workflow_inputs/processors_list.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/edit_query_modal.tsx
public/pages/workflow_detail/workflow_inputs/workflow_inputs.tsx
public/pages/workflow_detail/workspace/workspace.tsx
public/pages/workflow_detail/workspace/workspace_components/group_component.tsx
public/pages/workflow_detail/workspace/workspace_components/workspace_component.tsx
public/pages/workflows/empty_list_message.tsx
public/pages/workflows/new_workflow/use_case.tsx
public/pages/workflows/workflow_list/delete_workflow_modal.tsx
public/pages/workflows/workflow_list/workflow_list.tsx
public/pages/workflows/workflows.tsx

- Fit and Finish enhancements
- Fixed all header sizes 
- Added iconType "+ symbol" for create workflow button. 
- Changes all the button sizes to small
- Compressed tabs and Forms
- Changed the padding sizes where needed
- [] New functionality includes testing.

Fit and Finish enhancements

---

.github/workflows/remote-integ-tests-workflow.yml
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/edit_query_modal.tsx
public/pages/workflows/import_workflow/import_workflow_modal.tsx
public/pages/workflows/new_workflow/quick_configure_inputs.tsx

Added Integration Tests Workflow (backport 2.x)

Added Integration Tests Workflow (backport 2.x)

---

.github/workflows/remote-integ-tests-workflow.yml

- Updated Integration Tests Workflow to Resolve OpenSearch Dashboards Compile Issue seen in PR #434 
- Added compile step before Cypress runs 
Related to #434 

 Updated Integration Tests Workflow to Resolve OpenSearch Dashboards Compile Issue -2.x

---

common/constants.ts
public/general_components/processors_title.tsx
public/pages/workflow_detail/components/header.tsx
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/tools/tools.tsx
public/pages/workflow_detail/workflow_detail.test.tsx
public/pages/workflow_detail/workflow_inputs/ingest_inputs/source_data.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/map_array_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/map_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/input_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/modals/output_transform_modal.tsx
public/pages/workflow_detail/workflow_inputs/processors_list.tsx
public/pages/workflow_detail/workflow_inputs/search_inputs/configure_search_request.tsx

[Backport 2.x] Misc bug fixes and minor UX improvements II 

---

public/render_app.tsx

Flow framework is not using a correct router to render, it is using the router in Hash manner but renders the application with BrowserRouter, and it introduces many tricky behavior.
But as it changes the top Router, please do a thorough test to avoid regression issues. But it is a correct direction for making it right.
[List any issues this PR will resolve]
https://github.com/user-attachments/assets/dfdb3788-c411-4d4d-b258-addd69031af5

fix: use correct router

---

public/pages/workflows/workflows.tsx

- If mds is enabled, Added code to wait until selected data source is ready before doing dispatch calls 
- This is done to ensure workflow page(initial page) is properly loaded when mds is enabled. 
- Failing tests unrelated to this PR. 

Fix MDS bug

---

public/pages/workflows/new_workflow/new_workflow.tsx
public/pages/workflows/new_workflow/quick_configure_modal.tsx
public/pages/workflows/workflows.tsx
public/utils/utils.ts

- Added checks to verify if dataSourceId is ready before dispatching API calls.
- Fixed null pointer exceptions in Quick Configure

mds bug fixes 

---

release-notes/opensearch-flow-framework-dashboards.release-notes-2.19.0.0.md

Adds initial release notes for 2.19 release.

Add release notes for 2.19

---

public/pages/workflow_detail/workflow_inputs/search_inputs/search_inputs.tsx

Hide the whole search query section for version <2.19. Refactor the code in the search_input component. According the UI screenshot, the space between search_query and search_response has been removed.
[550](https://github.com/opensearch-project/dashboards-flow-framework/issues/550)

hide search query section when version is less than 2.19

---

server/routes/flow_framework_routes_service.ts
server/routes/opensearch_routes_service.ts

- Fixed bug related to Search Index in Local Cluster  scenario
closes #653 

Fixed bug related to Search Index in Local Cluster scenario

---

.github/workflows/changelog_verifier.yml
CHANGELOG.md
release-notes/opensearch-flow-framework-dashboards.release-notes-3.0.0.0-alpha1.md

Adding release notes for 3.0-alpha1
#304

Adding release notes for 3.0-alpha1

---

common/constants.ts
public/configs/search_response_processors/ml_search_response_processor.ts
public/pages/workflow_detail/workflow_inputs/input_fields/boolean_field.tsx
public/pages/workflow_detail/workflow_inputs/input_fields/text_field.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/ml_processor_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/model_inputs.tsx
public/pages/workflow_detail/workflow_inputs/processor_inputs/ml_processor_inputs/model_outputs.tsx
public/utils/config_to_template_utils.ts

Manual frontport of #699  to main.

[Backport main] Support whitespace for string constant; support ext toggling on ML resp processors

---

common/constants.ts
public/pages/workflow_detail/component_input/component_input.tsx
public/pages/workflow_detail/left_nav/left_nav.tsx
public/pages/workflow_detail/left_nav/nav_content/ingest_content.tsx
public/pages/workflow_detail/left_nav/nav_content/nav_components/nav_component.tsx
public/pages/workflow_detail/left_nav/nav_content/nav_components/processor_list.tsx
public/pages/workflow_detail/left_nav/nav_content/search_content.tsx
public/pages/workflow_detail/resizable_workspace.tsx
public/pages/workflow_detail/tools/query/query.tsx
public/pages/workflow_detail/tools/tools.tsx
public/pages/workflow_detail/workflow_detail.test.tsx
public/utils/form_to_pipeline_utils.ts

Misc updates to the left panel. More details:
- Modify selectable style to simply highlight the card, instead of the default `EuiCard` behavior, which includes a "Selected" button
- Adds option in the search tool to run with "only search request processors" to give more flexibility. Will likely be a default search from the left nav panel "Retrieve from data source" once UX is finalized.
- Fix all UT so it is passing
Screenshot of new highlighting style:
UT:
```
Test Suites: 6 passed, 6 total
Tests:       30 passed, 30 total
Snapshots:   0 total
Time:        13.43 s
Ran all test suites.
✨  Done in 14.76s.
```
For more information on following Developer Certificate of Origin …

More left panel changes; update UT

---

opensearch_dashboards.json
package.json

Backport 3.1 bump to feature branch so CI passes.

Increment version to 3.1.0.0 (#723)
